/Users/mcasl/pc-ule/Trabajo/investigacion/AMORE/AMORE-WC/AMORE-WC/pkg/AMORE/src/RcppModules.cpp File Reference
#include `package.h`
#include `classHeaders/NetworkRinterface.h`
Functions
RCPP_MODULE (modAMORE)
Function Documentation
RCPP_MODULE (modAMORE)
Definition at line 5 of file RcppModules.cpp.
References NetworkRinterface::createFeedForwardNetwork(), NetworkRinterface::inputSize(), NetworkRinterface::outputSize(), NetworkRinterface::predict(), NetworkRinterface::show(), and NetworkRinterface::validate().
  
    class_<NetworkRinterface>("NetworkRinterface")
    .constructor()
    .method("createFeedForwardNetwork", &
      NetworkRinterface::createFeedForwardNetwork)
    .method("predict", &NetworkRinterface::predict)
    .method("inputSize", &NetworkRinterface::inputSize)
    .method("outputSize", &NetworkRinterface::outputSize)
    .method("show", &NetworkRinterface::show)
    .method("validate", &NetworkRinterface::validate)
    ;
  