MLPbehavior Class Reference
class MLPbehavior -
#include <MLPbehavior.h>
Public Member Functions
MLPbehavior (NeuronPtr neuronPtr)
Private Member Functions
void singlePatternForwardAction ()
void show ()
Private Attributes
double d_bias
Friends
class MLPfactory
Detailed Description
class MLPbehavior -
Definition at line 5 of file MLPbehavior.h.
Constructor & Destructor Documentation
MLPbehavior::MLPbehavior (NeuronPtr neuronPtr)
Definition at line 17 of file MLPbehavior.cpp.
                                            :
   PredictBehavior(neuronPtr) , d_bias(0.0)
Member Function Documentation
void MLPbehavior::show () [private, virtual]
Implements PredictBehavior.
Definition at line 42 of file MLPbehavior.cpp.
References d_bias.
  Rprintf("bias: %lf", d_bias);
void MLPbehavior::singlePatternForwardAction () [private, virtual]
Implements PredictBehavior.
Definition at line 23 of file MLPbehavior.cpp.
References d_bias, PredictBehavior::getConIterator(), PredictBehavior::setInducedLocalField(), PredictBehavior::setOutput(), PredictBehavior::setOutputDerivative(), PredictBehavior::useActivationFunctionf0(), and PredictBehavior::useActivationFunctionf1().
  double accumulator(d_bias);
  ConIteratorPtr conIterator = getConIterator();
  double weight;
  double incomingSignalValue;
  for (conIterator->first(); !conIterator->isDone(); conIterator->next())
    
      weight = conIterator->currentItem()->getWeight();
      incomingSignalValue = conIterator->currentItem()->getNeuron().getOutput();
      accumulator += weight * incomingSignalValue;
    
  setInducedLocalField(accumulator);
  setOutput (useActivationFunctionf0());
  setOutputDerivative (useActivationFunctionf1());
Friends And Related Function Documentation
friend class MLPfactory [friend]
Definition at line 11 of file MLPbehavior.h.
Member Data Documentation
double MLPbehavior::d_bias [private]
Definition at line 8 of file MLPbehavior.h.
Referenced by MLPfactory::makeNeuron(), show(), and singlePatternForwardAction().
The documentation for this class was generated from the following files:
/Users/mcasl/pc-ule/Trabajo/investigacion/AMORE/AMORE-WC/AMORE-WC/pkg/AMORE/src/classHeaders/MLPbehavior.h
/Users/mcasl/pc-ule/Trabajo/investigacion/AMORE/AMORE-WC/AMORE-WC/pkg/AMORE/src/MLPbehavior.cpp