NetworkRinterface Class Reference
class NetworkRinterface -
#include <NetworkRinterface.h>
Public Member Functions
NetworkRinterface ()
void createFeedForwardNetwork (Rcpp::NumericVector numberOfNeurons)
Rcpp::NumericMatrix predict (Rcpp::NumericMatrix numericMatrix)
size_type inputSize ()
size_type outputSize ()
void show ()
bool validate ()
Private Attributes
NeuralNetworkPtr d_neuralNetwork
Detailed Description
class NetworkRinterface -
Definition at line 3 of file NetworkRinterface.h.
Constructor & Destructor Documentation
NetworkRinterface::NetworkRinterface ()
Definition at line 22 of file NetworkRinterface.cpp.
Member Function Documentation
void NetworkRinterface::createFeedForwardNetwork (Rcpp::NumericVector numberOfNeurons)
Definition at line 28 of file NetworkRinterface.cpp.
References d_neuralNetwork.
Referenced by RCPP_MODULE().
  NeuralFactoryPtr hiddenLayersFactoryPtr(new TanhFactory());
  NeuralFactoryPtr outputFactoryPtr(new IdentityFactory());
  NeuralCreatorPtr neuralCreator(outputFactoryPtr->makeNeuralCreator());
  d_neuralNetwork = neuralCreator->createFeedForwardNetwork(
      as<std::vector<int> > (numberOfNeurons), *hiddenLayersFactoryPtr,
      *outputFactoryPtr);
size_type NetworkRinterface::inputSize ()
Definition at line 70 of file NetworkRinterface.cpp.
References d_neuralNetwork.
Referenced by predict(), and RCPP_MODULE().
  return d_neuralNetwork->inputSize();
size_type NetworkRinterface::outputSize ()
Definition at line 76 of file NetworkRinterface.cpp.
References d_neuralNetwork.
Referenced by predict(), and RCPP_MODULE().
  return d_neuralNetwork->outputSize();
Rcpp::NumericMatrix NetworkRinterface::predict (Rcpp::NumericMatrix numericMatrix)
Definition at line 39 of file NetworkRinterface.cpp.
References d_neuralNetwork, inputSize(), and outputSize().
Referenced by RCPP_MODULE().
  BEGIN_RCPP
  if (!d_neuralNetwork)
    
      throw std::runtime_error("network. Please use any of the c
      reate methods available.");
    
  bool checkIncorrectNumberOfRows(
      inputSize() != static_cast<size_type> (numericMatrix.nrow()));
  if (checkIncorrectNumberOfRows)
    
      throw std::runtime_error(
          "number or rows. The number of input neurons must be equal
      to the number of rows of the input matrix.");
    
  Rcpp::NumericMatrix outputMatrix(outputSize(), numericMatrix.ncol());
  std::vector<double>::iterator inputIterator(numericMatrix.begin());
  std::vector<double>::iterator outputIterator(outputMatrix.begin());
  for (int i = 0; i < numericMatrix.ncol(); i++)
    
      d_neuralNetwork->writeInput(inputIterator);
      d_neuralNetwork->predict();
      d_neuralNetwork->readOutput(outputIterator);
    
  return outputMatrix;
END_RCPP
void NetworkRinterface::show ()
Definition at line 82 of file NetworkRinterface.cpp.
References d_neuralNetwork.
Referenced by RCPP_MODULE().
  if (!d_neuralNetwork)
    
      Rprintf(
          "network. Please use any of the create methods availabl
      e.");
    
  else
    
      d_neuralNetwork->show();
    
bool NetworkRinterface::validate ()
Definition at line 97 of file NetworkRinterface.cpp.
References d_neuralNetwork.
Referenced by RCPP_MODULE().
BEGIN_RCPP if (d_neuralNetwork)
  
    return d_neuralNetwork->validate();
  
else
  
    throw std::runtime_error(
        "network. Please use any of the create methods available.
      ");
    return false;
  
END_RCPP
Member Data Documentation
NeuralNetworkPtr NetworkRinterface::d_neuralNetwork [private]
Definition at line 6 of file NetworkRinterface.h.
Referenced by createFeedForwardNetwork(), inputSize(), outputSize(), predict(), show(), and validate().
The documentation for this class was generated from the following files:
/Users/mcasl/pc-ule/Trabajo/investigacion/AMORE/AMORE-WC/AMORE-WC/pkg/AMORE/src/classHeaders/NetworkRinterface.h
/Users/mcasl/pc-ule/Trabajo/investigacion/AMORE/AMORE-WC/AMORE-WC/pkg/AMORE/src/NetworkRinterface.cpp