Neuron Class Reference
class Neuron -
#include <Neuron.h>
Public Member Functions
Neuron ()
Neuron (int Id)
Neuron (int Id, Container< Con >::const_iterator firstCon, Container< Con >::const_iterator lastCon)
int getId ()
void setId (int Id)
void iterators (Container< Con >::iterator &first, Container< Con >::iterator &last)
void const_iterators (Container< Con >::const_iterator &first, Container< Con >::const_iterator &last)
void show ()
bool validate ()
Neuron ()
Neuron (int Id)
Neuron (int Id, ConContainer con)
~Neuron ()
int getId ()
void setId (int value)
std::vector< int > getConId ()
std::vector< double > getWeight ()
bool setFrom (NeuronContainer neuronContainer)
bool setWeight (std::vector< double > nWeights)
int numOfCons ()
bool show ()
bool validate ()
Protected Attributes
int Id
An integer variable with the Neuron Id.
Container< Con > nCons
Private Attributes
ConContainer con
A vector of input connections.
double outputValue
Detailed Description
class Neuron -
A class to handle the information contained in a general Neuron.
A general class for neurons. The MLPneuron and RBFneuron classes will specialize this general class
Definition at line 5 of file Neuron.h.
Constructor & Destructor Documentation
Neuron::Neuron ()
Definition at line 10 of file Neuron.cpp.
               :
  Id(NA_INTEGER), nCons()
Neuron::Neuron (int Id)
Definition at line 15 of file Neuron.cpp.
                     :
  Id(Id), nCons()
Neuron::Neuron (int Id, Container< Con >::const_iterator firstCon, Container< Con >::const_iterator lastCon)
Definition at line 20 of file Neuron.cpp.
References Container< T >::begin(), Container< T >::insert(), and nCons.
                                                                                 
                        :
  Id(Id), nCons()
  nCons.insert(nCons.begin(), firstCon, lastCon);
Neuron::Neuron ()
Neuron::Neuron (int Id)
Neuron::Neuron (int Id, ConContainer con)
Neuron::~Neuron ()
Member Function Documentation
void Neuron::const_iterators (Container< Con >::const_iterator & first, Container< Con >::const_iterator & last)
Definition at line 50 of file Neuron.cpp.
References Container< T >::begin(), Container< T >::end(), and nCons.
   first=nCons.begin();
    last=nCons.end();
std::vector<int> Neuron::getConId ()
int Neuron::getId ()
Definition at line 29 of file Neuron.cpp.
References Id.
Referenced by show(), and validate().
  return Id;
int Neuron::getId ()
std::vector<double> Neuron::getWeight ()
void Neuron::iterators (Container< Con >::iterator & first, Container< Con >::iterator & last)
Definition at line 42 of file Neuron.cpp.
References Container< T >::begin(), Container< T >::end(), and nCons.
   first=nCons.begin();
    last=nCons.end();
int Neuron::numOfCons ()
bool Neuron::setFrom (NeuronContainer neuronContainer)
void Neuron::setId (int Id)
Definition at line 35 of file Neuron.cpp.
References Id.
  Id = value;
void Neuron::setId (int value)
bool Neuron::setWeight (std::vector< double > nWeights)
bool Neuron::show ()
Definition at line 58 of file Neuron.cpp.
References getId(), nCons, Container< T >::show(), and Container< T >::size().
  int id = getId();
  Rprintf("------------------------");
  if (id == NA_INTEGER)
    
      Rprintf("Id: NA, Invalid neuron Id");
    
  else
    
      Rprintf("Id: %d", id);
    
  Rprintf("------------------------");
  if (nCons.size() == 0)
    
      Rprintf("No connections defined");
    
  else
    
      nCons.show();
    
  Rprintf("------------------------");
 
bool Neuron::show ()
bool Neuron::validate ()
bool Neuron::validate ()
Definition at line 84 of file Neuron.cpp.
References getId().
  BEGIN_RCPP
  if (getId() == NA_INTEGER) throw std::range_error("[C++ Neuron::validate]: Err
      or, Id is NA.");
 // nCons.validate();
  return (TRUE);
END_RCPP
Member Data Documentation
ConContainer Neuron::con [private]
A vector of input connections.
Definition at line 29 of file Neuron.h.
int Neuron::Id [protected]
An integer variable with the Neuron Id.
The Neuron Id provides a name to the neuron. This value is not expected to be used neither during simulation nor training but it provides an easy reference for human readers.
Definition at line 8 of file Neuron.h.
Referenced by getId(), and setId().
Container<Con> Neuron::nCons [protected]
Definition at line 9 of file Neuron.h.
Referenced by const_iterators(), iterators(), Neuron(), and show().
double Neuron::outputValue [private]
Definition at line 30 of file Neuron.h.
The documentation for this class was generated from the following files:
pkg/AMORE/src/Neuron.h
pkg/AMORE/src/old/Neuron.h
pkg/AMORE/src/Neuron.cpp
pkg/AMORE/src/old/Neuron.cpp