Container< T > Class Template Reference
class Container -
#include <Container.h>
Public Types
typedef std::vector< boost::shared_ptr< T > >::iterator iterator
typedef std::vector< boost::shared_ptr< T > >::const_iterator const_iterator
typedef boost::shared_ptr< T > value_type
typedef value_type const & const_reference
Public Member Functions
Container ()
~Container ()
boost::shared_ptr< IteratorInterface< T > > createIterator ()
void push_back (T const &const_reference)
Append a shared_ptr at the end of collection.
void reserve (int n)
bool empty ()
size_type size ()
Returns the size or length of the vector.
void clear ()
void show ()
Pretty print of the Container<T>
bool validate ()
Object validator.
Container ()
Container (std::vector< value > first, std::vector< value > last)
iterator begin ()
iterator end ()
std::vector< boost::shared_ptr< T > > load ()
collection field accessor function
void store (typename std::vector< boost::shared_ptr< T > > collectionT)
collection field accessor function
size_type size ()
void push_back (boost::shared_ptr< T > const &const_reference)
Append a shared_ptr at the end of collection.
void append (Container< T > containerT)
Appends a Container<T> object.
bool show ()
bool validate ()
void reserve (int n)
void resize (int n)
bool empty ()
void clear ()
boost::shared_ptr< T > & operator[] (size_type offset)
Protected Attributes
std::vector< T > collection
std::vector< boost::shared_ptr< T > > collection
Friends
class ContainerIterator< T >
Detailed Description
template<typename T>class Container< T >
class Container -
Definition at line 6 of file Container.h.
Member Typedef Documentation
template<typename T> typedef std::vector<boost::shared_ptr<T> >::const_iterator Container< T >::const_iterator
Reimplemented in ConContainer, and NeuronContainer.
Definition at line 22 of file Container.h.
template<typename T> typedef value_type const& Container< T >::const_reference
Reimplemented in ConContainer, and NeuronContainer.
Definition at line 26 of file Container.h.
template<typename T> typedef std::vector<boost::shared_ptr<T> >::iterator Container< T >::iterator
Reimplemented in ConContainer, and NeuronContainer.
Definition at line 19 of file Container.h.
template<typename T> typedef boost::shared_ptr<T> Container< T >::value_type
Reimplemented in ConContainer, and NeuronContainer.
Definition at line 24 of file Container.h.
Constructor & Destructor Documentation
template<typename T > Container< T >::Container ()
Definition at line 11 of file Container.cpp.
  
  
template<typename T > Container< T >::~Container ()
Definition at line 17 of file Container.cpp.
  
  
template<typename T> Container< T >::Container ()
template<typename T> Container< T >::Container (std::vector< value > first, std::vector< value > last)
Member Function Documentation
template<typename T> void Container< T >::append (Container< T > v)
Appends a Container<T> object.
This method inserts the collection field of a second object at the end of the collection field of the calling object.
Parameters
v The Container<T> object to be added to the current one
See also
The unit test files, e.g., runit.Cpp.Container.R, for usage examples.
        //================
        //Usage example:
        //================
        // Data set up
                                std::vector<int> result;
                                std::vector<ConPtr> vcA, vcB;
                                ContainerNeuronPtr neuronContainerPtr(new
      Container<Neuron>());
                                ContainerConPtr conContainerPtrA(new
      Container<Con>());
                                ContainerConPtr conContainerPtrB(new
      Container<Con>());
                                ConPtr ptC;
                                NeuronPtr ptN;
                                int ids[]= 1, 2, 3, 4, 5, 6;
                                double weights[] = 1.13, 2.22, 3.33, 5.6, 4.2, 3
      .6 ;
                                for (int i=0; i<=5 ; i++) /
      / Let's create a vector with six neurons
                                        ptN.reset(new Neuron(ids[i]));
                                        neuronContainerPtr->push_back(ptN);
                                
                                for (int i=0; i<=2 ; i++) /
      / A vector with three connections
                                        ptC.reset(new Con(neuronContainerPtr->l
      oad().at(i), weights[i]));
                                        conContainerPtrA->push_back(ptC);
                                
                                for (int i=3; i<=5 ; i++) /
      / Another vector with three connections
                                        ptC.reset(new Con(neuronContainerPtr->l
      oad().at(i), weights[i]));
                                        conContainerPtrB->push_back(ptC);
                                
        // Test
                                conContainerPtrA->append(*conContainerPtrB);
                                conContainerPtrA->validate();
                                conContainerPtrA->show() ;
        // After execution of the code above, the output at the R terminal would
      display:
        //
        // From: 1 Weight= 1.130000
        // From: 2 Weight= 2.220000
        // From: 3 Weight= 3.330000
        // From: 4 Weight= 5.600000
        // From: 5 Weight= 4.200000
        // From: 6 Weight= 3.600000
See also
Container::store , Container::push_back and the unit test files, e.g., runit.Cpp.Container.R, for usage examples.
Definition at line 207 of file Container.cpp.
References Container< T >::begin(), Container< T >::end(), and Container< T >::size().
  
    reserve(size() + v.size());
    collection.insert(end(), v.begin(), v.end());
  
template<typename T > std::vector< boost::shared_ptr< T > >::iterator Container< T >::begin ()
Definition at line 22 of file Container.cpp.
Referenced by Container< T >::append(), and ConContainer::setFrom().
  
    return collection.begin();
  
template<typename T > void Container< T >::clear () [virtual]
Implements ContainerInterface< T >.
Definition at line 177 of file Container.cpp.
  
    collection.clear();
  
template<typename T> void Container< T >::clear () [virtual]
Implements ContainerInterface< T >.
template<typename T > boost::shared_ptr< IteratorInterface< T > > Container< T >::createIterator () [virtual]
Implements ContainerInterface< T >.
Definition at line 23 of file Container.cpp.
  
    boost::shared_ptr< ContainerIterator<T> > containerIteratorPtr(new
      ContainerIterator<T> ());
    containerIteratorPtr->d_container = this;
    containerIteratorPtr->d_iterator = collection.begin();
    return containerIteratorPtr;
  
template<typename T > bool Container< T >::empty () [virtual]
Implements ContainerInterface< T >.
Definition at line 163 of file Container.cpp.
Referenced by ConContainer::setFrom().
  
    return (collection.empty());
  
template<typename T> bool Container< T >::empty () [virtual]
Implements ContainerInterface< T >.
template<typename T > std::vector< boost::shared_ptr< T > >::iterator Container< T >::end ()
Definition at line 29 of file Container.cpp.
Referenced by Container< T >::append().
  
    return collection.end();
  
template<typename T > std::vector< boost::shared_ptr< T > > Container< T >::load ()
collection field accessor function
This method allows access to the data stored in the collection field.
Returns
The collection vector.
        //================
        //Usage example:
        //================
                // Data set up
                                std::vector<int> result;
                                std::vector<ConPtr> vcA, vcB;
                                ContainerNeuronPtr neuronContainerPtr(new
      Container<Neuron>());
                                ContainerConPtr conContainerPtr(new
      Container<Con>());
                                ConPtr ptC;
                                NeuronPtr ptN;
                                int ids[]= 10, 20, 30;
                                double weights[] = 1.13, 2.22, 3.33 ;
                                for (int i=0; i<=2 ; i++) /
      / Let's create a vector with three neurons
                                        ptN.reset(new Neuron(ids[i]));
                                        neuronContainerPtr->push_back(ptN);
                                
                                for (int i=0; i<=2 ; i++) /
      / and a vector with three connections
                                        ptC.reset(new Con(neuronContainerPtr->l
      oad().at(i), weights[i]));
                                        vcA.push_back(ptC);
                                
                // Test
                        conContainerPtr->store(vcA);
                        vcB = conContainerPtr->load();
                        for (int i=0; i<=2 ; i++) /
      / get Ids. Container does not have getId defined
                                        result.push_back(vcB.at(i)->getId());
                        
                // Now, result is an integer vector with values 10, 20, 30.
See also
store and the unit test files, e.g., runit.Cpp.Container.R, for usage examples.
Definition at line 254 of file Container.cpp.
  
    return collection;
  
template<typename T > boost::shared_ptr< T > & Container< T >::operator[] (size_type offset)
Definition at line 317 of file Container.cpp.
  
    return collection[offset];
  
template<typename T> void Container< T >::push_back (T const & reference) [virtual]
Append a shared_ptr at the end of collection.
Implements push_back for the Container class
Parameters
TsharedPtr A shared_ptr pointer to be inserted at the end of collection
                //================
                //Usage example:
                //================
                // Data set up
                        Neuron N1, N2, N3;
                        Container<Con> conContainer;
                        std::vector<ConPtr> vc;
                        std::vector<int> result;
                        N1.setId(10);
                        N2.setId(20);
                        N3.setId(30);
                // Test
                        ConPtr ptCon(new Con(&N1, 1.13)); // Create new Con
       and initialize ptCon
                        conContainer.push_back(ptCon); /
      / push_back
                        ptCon.reset(new Con(&N2, 2.22)); // create
       new Con and assign to ptCon
                        conContainer.push_back(ptCon); /
      / push_back
                        ptCon.reset(new Con(&N3, 3.33)); // create
       new Con and assign to ptCon
                        conContainer.push_back(ptCon); /
      / push_back
                        vc = conContainer.load();
                        result.push_back(vc.at(0)->getId());
                        result.push_back(vc.at(1)->getId());
                        result.push_back(vc.at(2)->getId());
        // After execution of this code, result contains a numeric vector with va
      lues 10, 20 and 30.
See also
C++ documentation for std::vector::push_back and the unit test files, e.g., runit.Cpp.Container.R, for usage examples.
Implements ContainerInterface< T >.
Definition at line 68 of file Container.cpp.
  
    collection.push_back(reference);
  
template<typename T> void Container< T >::push_back (boost::shared_ptr< T > const & const_reference)
Append a shared_ptr at the end of collection.
Implements push_back for the Container class
Parameters
TsharedPtr A shared_ptr pointer to be inserted at the end of collection
                //================
                //Usage example:
                //================
                // Data set up
                        Neuron N1, N2, N3;
                        Container<Con> conContainer;
                        std::vector<ConPtr> vc;
                        std::vector<int> result;
                        N1.setId(10);
                        N2.setId(20);
                        N3.setId(30);
                // Test
                        ConPtr ptCon(new Con(&N1, 1.13)); // Create new Con
       and initialize ptCon
                        conContainer.push_back(ptCon); /
      / push_back
                        ptCon.reset(new Con(&N2, 2.22)); // create
       new Con and assign to ptCon
                        conContainer.push_back(ptCon); /
      / push_back
                        ptCon.reset(new Con(&N3, 3.33)); // create
       new Con and assign to ptCon
                        conContainer.push_back(ptCon); /
      / push_back
                        vc = conContainer.load();
                        result.push_back(vc.at(0)->getId());
                        result.push_back(vc.at(1)->getId());
                        result.push_back(vc.at(2)->getId());
        // After execution of this code, result contains a numeric vector with va
      lues 10, 20 and 30.
See also
C++ documentation for std::vector::push_back and the unit test files, e.g., runit.Cpp.Container.R, for usage examples.
Definition at line 71 of file Container.cpp.
  
    collection.push_back(const_reference);
  
template<typename T> void Container< T >::reserve (int n) [virtual]
Implements ContainerInterface< T >.
template<typename T > void Container< T >::reserve (int n) [virtual]
Implements ContainerInterface< T >.
Definition at line 170 of file Container.cpp.
  
    collection.reserve(n);
  
template<typename T > void Container< T >::resize (int n)
Definition at line 289 of file Container.cpp.
  
    collection.resize(n);
  
template<typename T> bool Container< T >::show () [virtual]
Implements ContainerInterface< T >.
template<typename T > bool Container< T >::show () [virtual]
Pretty print of the Container<T>
This method outputs in the R terminal the contents of Container::collection.
Returns
true in case everything works without throwing an exception
*
                //================
                //Usage example:
                //================
                // Data set up
                        ContainerNeuronPtr neuronContainerPtr(new
      Container<Neuron>());
                        ContainerConPtr conContainerPtr(new Container<Con>());
                        ConPtr ptC;
                        NeuronPtr ptN;
                        int ids[]= 10, 20, 30;
                        double weights[] = 1.13, 2.22, 3.33 ;
                        for (int i=0; i<=2 ; i++) /
      / Let's create a vector with three neurons
                                ptN.reset(new Neuron(ids[i]));
                                neuronContainerPtr->push_back(ptN);
                        
                        for (int i=0; i<=2 ; i++) /
      / and a vector with three connections
                                ptC.reset(new Con(neuronContainerPtr->load().at
      (i), weights[i]));
                                conContainerPtr->push_back(ptC);
                        
                // Test
                        conContainerPtr->show() ;
                // The output at the R terminal would display:
                //
                // # From: 10 Weight= 1.130000
                // # From: 20 Weight= 2.220000
                // # From: 30 Weight= 3.330000
                //
See also
The unit test files, e.g., runit.Cpp.Container.R, for usage examples.
Implements ContainerInterface< T >.
Definition at line 118 of file Container.cpp.
  
    for (typename std::vector<T>::iterator itr(collection.begin()); itr
        != collection.end(); ++itr)
      
        itr->show();
      
  
template<typename T> size_type Container< T >::size () [virtual]
Implements ContainerInterface< T >.
template<typename T > size_type Container< T >::size () [virtual]
Returns the size or length of the vector.
This method returns the size of the vector. In the classes derived from Container<T> this is aliased as numOfCons, numOfNeurons and numOfLayers. The unit test files, e.g., runit.Cpp.Container.R, for usage examples.
Implements ContainerInterface< T >.
Definition at line 155 of file Container.cpp.
Referenced by Container< T >::append(), and ConContainer::setFrom().
  
    return collection.size();
  
template<typename T> void Container< T >::store (typename std::vector< boost::shared_ptr< T > > collectionT)
collection field accessor function
This method sets the value of the data stored in the collection field.
Parameters
v The vector of smart pointers to be stored in the collection field
See also
load and the unit test files, e.g., runit.Cpp.Container.R, for usage examples.
Definition at line 268 of file Container.cpp.
  
    collection = collectionT;
  
template<typename T> bool Container< T >::validate () [virtual]
Implements ContainerInterface< T >.
Reimplemented in ConContainer.
template<typename T > bool Container< T >::validate () [virtual]
Object validator.
This method checks the object for internal coherence. This method calls the validate method for each element in collection,
See also
The unit test files, e.g., runit.Cpp.Container.R, for usage examples.
Implements ContainerInterface< T >.
Reimplemented in ConContainer.
Definition at line 136 of file Container.cpp.
  
    for (typename std::vector<T>::iterator itr(collection.begin()); itr
        != collection.end(); ++itr)
      
        itr->validate();
      
    return true;
  
Friends And Related Function Documentation
template<typename T> friend class ContainerIterator< T > [friend]
Definition at line 12 of file Container.h.
Member Data Documentation
template<typename T> std::vector< T > Container< T >::collection [protected]
Definition at line 9 of file Container.h.
template<typename T> std::vector<boost::shared_ptr<T> > Container< T >::collection [protected]
Definition at line 15 of file Container.h.
The documentation for this class was generated from the following files:
pkg/AMORE/src/dia/Container.h
pkg/AMORE/src/old/Container.h
pkg/AMORE/src/Container.cpp
pkg/AMORE/src/old/Container.cpp