SimpleNetwork Class Reference
class SimpleNetwork -
#include <SimpleNetwork.h>
Public Member Functions
SimpleNetwork (NeuralFactory &neuralFactory)
Private Member Functions
void writeInput (std::vector< double >::iterator &iterator)
void singlePatternForwardAction ()
void singlePatternBackwardAction ()
void readOutput (std::vector< double >::iterator &iterator)
Rcpp::List train (Rcpp::List parameterList)
size_type inputSize ()
size_type outputSize ()
void show ()
bool validate ()
Detailed Description
class SimpleNetwork -
Definition at line 5 of file SimpleNetwork.h.
Constructor & Destructor Documentation
SimpleNetwork::SimpleNetwork (NeuralFactory & neuralFactory)
Definition at line 16 of file SimpleNetwork.cpp.
                                                         :
  NeuralNetwork(neuralFactory)
Member Function Documentation
size_type SimpleNetwork::inputSize () [private, virtual]
Implements NeuralNetwork.
Definition at line 108 of file SimpleNetwork.cpp.
References NeuralNetwork::d_inputLayer.
Referenced by writeInput().
  return d_inputLayer->size();
size_type SimpleNetwork::outputSize () [private, virtual]
Implements NeuralNetwork.
Definition at line 114 of file SimpleNetwork.cpp.
References NeuralNetwork::d_outputLayer.
Referenced by readOutput().
  return d_outputLayer->size();
void SimpleNetwork::readOutput (std::vector< double >::iterator & iterator) [private, virtual]
Implements NeuralNetwork.
Definition at line 88 of file SimpleNetwork.cpp.
References NeuralNetwork::d_outputLayer, outputSize(), and size_type.
  size_type nOutputs(outputSize());
  for (size_type i = 0; i < nOutputs; i++)
    
      *iterator++ = d_outputLayer->at(i)->getOutput();
    
void SimpleNetwork::show () [private, virtual]
Implements NeuralNetwork.
Definition at line 120 of file SimpleNetwork.cpp.
References NeuralNetwork::d_hiddenLayers, NeuralNetwork::d_inputLayer, and NeuralNetwork::d_outputLayer.
  Rprintf("=========================================================");
  Rprintf(" Input Layer");
  Rprintf("=========================================================");
  d_inputLayer->show();
  Rprintf("=========================================================");
  Rprintf(" Hidden Layers");
  Rprintf("=========================================================");
  d_hiddenLayers->show();
  Rprintf("=========================================================");
  Rprintf(" Output Layer");
  Rprintf("=========================================================");
  d_outputLayer->show();
  Rprintf("=========================================================");
void SimpleNetwork::singlePatternBackwardAction () [private, virtual]
Implements NeuralNetwork.
Definition at line 64 of file SimpleNetwork.cpp.
References NeuralNetwork::d_hiddenLayers, and NeuralNetwork::d_outputLayer.
  // Output Layers
  boost::shared_ptr < Iterator<NeuronPtr> > neuronIterator(d_outputLayer->createR
      everseIterator());
  for (neuronIterator->first(); !neuronIterator->isDone(); neuronIterator->next()
      )
    
      neuronIterator->currentItem()->singlePatternBackwardAction();
    
  // Hidden Layers
  boost::shared_ptr < Iterator<LayerPtr> > layerIterator(d_hiddenLayers->createRe
      verseIterator());
  for (layerIterator->first(); !layerIterator->isDone(); layerIterator->next())
    
      boost::shared_ptr < Iterator<NeuronPtr> > neuronIterator(layerIterator->cu
      rrentItem()->createReverseIterator());
      for (neuronIterator->first(); !neuronIterator->isDone(); neuronIterator->ne
      xt())
        
          neuronIterator->currentItem()->singlePatternBackwardAction();
        
    
void SimpleNetwork::singlePatternForwardAction () [private, virtual]
Implements NeuralNetwork.
Definition at line 35 of file SimpleNetwork.cpp.
References NeuralNetwork::d_hiddenLayers, and NeuralNetwork::d_outputLayer.
  // Hidden Layers
  boost::shared_ptr < Iterator<LayerPtr> > layerIterator(
      d_hiddenLayers->createIterator());
  for (layerIterator->first(); !layerIterator->isDone(); layerIterator->next())
    
      boost::shared_ptr < Iterator<NeuronPtr> > neuronIterator(
          layerIterator->currentItem()->createIterator());
      for (neuronIterator->first(); !neuronIterator->isDone(); neuronIterator->ne
      xt())
        
          neuronIterator->currentItem()->singlePatternForwardAction();
        
    
  // Output Layers
  boost::shared_ptr < Iterator<NeuronPtr> > neuronIterator(
      d_outputLayer->createIterator());
  for (neuronIterator->first(); !neuronIterator->isDone(); neuronIterator->next()
      )
    
      neuronIterator->currentItem()->singlePatternForwardAction();
    
Rcpp::List SimpleNetwork::train (Rcpp::List parameterList) [private, virtual]
Implements NeuralNetwork.
Definition at line 98 of file SimpleNetwork.cpp.
References NeuralNetwork::d_networkTrainBehavior.
  // TODO check train behavior and change it if need be
  // TODO check cost function and change it if need be
  return d_networkTrainBehavior->train(parameterList);
bool SimpleNetwork::validate () [private, virtual]
Implements NeuralNetwork.
Definition at line 141 of file SimpleNetwork.cpp.
References NeuralNetwork::d_hiddenLayers, NeuralNetwork::d_inputLayer, and NeuralNetwork::d_outputLayer.
  d_inputLayer->validate();
  d_hiddenLayers->validate();
  d_outputLayer->validate();
  return true;
void SimpleNetwork::writeInput (std::vector< double >::iterator & iterator) [private, virtual]
Implements NeuralNetwork.
Definition at line 23 of file SimpleNetwork.cpp.
References NeuralNetwork::d_inputLayer, inputSize(), and size_type.
  size_type nInputs(inputSize());
  for (size_type i = 0; i < nInputs; i++)
    
      d_inputLayer->at(i)->setOutput(*iterator++);
    
The documentation for this class was generated from the following files:
/Users/mcasl/pc-ule/Trabajo/investigacion/AMORE/AMORE-WC/AMORE-WC/pkg/AMORE/src/classHeaders/SimpleNetwork.h
/Users/mcasl/pc-ule/Trabajo/investigacion/AMORE/AMORE-WC/AMORE-WC/pkg/AMORE/src/SimpleNetwork.cpp