ConContainer Class Reference
A vector of connections.
#include <ConContainer.h>
Public Types
typedef std::vector< boost::shared_ptr< Con > >::iterator iterator
typedef std::vector< boost::shared_ptr< Con > >::const_iterator const_iterator
typedef boost::shared_ptr< Con > value_type
typedef value_type const & const_reference
Public Member Functions
ConContainer ()
ConContainer (std::vector< ConPtr > collection)
int numOfCons ()
Size of the ConContainer object.
std::vector< int > getId ()
Getter of the Id values of the vector of Cons.
bool setWeight (std::vector< double > nWeights)
Setter of the weight field of the Con objects related to ConContainer.
bool setWeight (std::vector< double > nWeights, std::vector< int > nIds)
Setter of the weights of the specified elements from the ConContainer object.
bool setFrom (NeuronContainer neuronContainer)
Setter of the from fields of the Con objects related to ConContainer.
void erase (std::vector< int > nIds)
Erase the specified elements from the vecCom object.
ConContainerPtr select (std::vector< int > nIds)
Selects the specified elements from the vecCom object.
bool validate ()
Object validator.
Detailed Description
A vector of connections.
The ConContainer class provides a simple class for a vector of connections. It's named after the R equivalent Reference Class.
Definition at line 16 of file ConContainer.h.
Member Typedef Documentation
typedef std::vector<boost::shared_ptr<Con> >::const_iterator ConContainer::const_iterator
Reimplemented from Container< Con >.
Definition at line 23 of file ConContainer.h.
typedef value_type const& ConContainer::const_reference
Reimplemented from Container< Con >.
Definition at line 27 of file ConContainer.h.
typedef std::vector<boost::shared_ptr<Con> >::iterator ConContainer::iterator
Reimplemented from Container< Con >.
Definition at line 21 of file ConContainer.h.
typedef boost::shared_ptr<Con> ConContainer::value_type
Reimplemented from Container< Con >.
Definition at line 25 of file ConContainer.h.
Constructor & Destructor Documentation
ConContainer::ConContainer ()
Definition at line 8 of file ConContainer.cpp.
ConContainer::ConContainer (std::vector< ConPtr > collection)
Definition at line 12 of file ConContainer.cpp.
                                                       :
  Container<Con> (collection) // Call to Base constructor
Member Function Documentation
void ConContainer::erase (std::vector< int > nIds)
Erase the specified elements from the vecCom object.
Provides a convenient way of removing some Con objects from the collection field of the ConContainer object.
Parameters
vFrom An std::vector<int> with the Ids of the connections to remove.
        //================
        //Usage example:
        //================
        // Data set up
                        std::vector<int> result;
                        std::vector<NeuronPtr> neuronContainer;
                        ConContainerPtr conContainerPtr(new ConContainer());
                        ConContainerPtr vErased;
                        ConPtr ptC;
                        NeuronPtr ptN;
                        int ids[]= 11, 10, 9, 3, 4, 5, 6, 7, 8, 2, 1;
                        std::vector<double> nWeights;
                        nWeights.push_back(11.32);
                        nWeights.push_back(1.26);
                        nWeights.push_back(2.14);
                        nWeights.push_back(3.16);
                        nWeights.push_back(4.14);
                        nWeights.push_back(5.19);
                        nWeights.push_back(6.18);
                        nWeights.push_back(7.16);
                        nWeights.push_back(8.14);
                        nWeights.push_back(9.12);
                        nWeights.push_back(10.31);
                        for (int i=0; i<nWeights.size() ; i++) /
      / Let's create a vector with three neurons
                                ptN.reset(new Neuron(ids[i]));
                                neuronContainer.push_back(ptN);
                        
                        conContainerPtr->buildAndAppend(neuronContainer, nWeights
      );
                        // Test
                        std::vector<int> toRemove;
                        toRemove.push_back(1);
                        toRemove.push_back(3);
                        toRemove.push_back(5);
                        toRemove.push_back(7);
                        conContainerPtr->erase(toRemove);
                        conContainerPtr->show();
                        result=conContainerPtr->getId();
                // The output at the R terminal would display :
                //
                // From: 2 Weight= 9.120000
                // From: 4 Weight= 4.140000
                // From: 6 Weight= 6.180000
                // From: 8 Weight= 8.140000
                // From: 9 Weight= 2.140000
                // From: 10 Weight= 1.260000
                // From: 11 Weight= 11.320000
See also
select and the unit test files, e.g. runit.Cpp.ConContainer.R, for further examples.
Definition at line 450 of file ConContainer.cpp.
References Container< Con >::begin(), Container< Con >::end(), and Container< Con >::resize().
  std::vector<ConPtr>::iterator itr;
  sort(begin(), end(), CompareId());
  sort(nIds.begin(), nIds.end());
  itr = set_difference(begin(), end(), nIds.begin(), nIds.end(), begin(),
      CompareId());
  resize(itr - begin());
std::vector< int > ConContainer::getId ()
Getter of the Id values of the vector of Cons.
This function returns the Id's of the neurons referred to by the vector of Cons.
Returns
An std::vector<int> that contains the Ids
  //================
  //Usage example:
  //================
        // Data set up
                        Neuron N1, N2, N3;
                        ConContainer conContainer;
                        std::vector<int> result;
                        N1.setId(10);
                        N2.setId(20);
                        N3.setId(30);
                        ConPtr ptCon(new Con(&N1, 1.13)); // Create new Con
       and initialize ptCon
                        conContainer.push_back(ptCon); /
      / push_back
                        ptCon.reset(new Con(&N2, 2.22)); // create
       new Con and assign to ptCon
                        conContainer.push_back(ptCon); /
      / push_back
                        ptCon.reset(new Con(&N3, 3.33)); // create
       new Con and assign to ptCon
                        conContainer.push_back(ptCon); /
      / push_back
        // Test
                        conContainer.show() ;
                        conContainer.validate();
                        result=conContainer.getId();
        // Now result is a vector that contains the values 10, 20 and 30.
See also
getWeight and the unit test files, e.g. runit.Cpp.ConContainer.R, for further examples.
Definition at line 93 of file ConContainer.cpp.
References numOfCons().
Referenced by validate().
  std::vector<int> result;
  result.reserve(numOfCons());
  foreach (ConPtr itr, *this)
    
      result.push_back(itr->getId());
    
  return result;
int ConContainer::numOfCons ()
Size of the ConContainer object.
This function returns the size of the ConContainer object, that is to say, the number of Con objects it contains.
Returns
The size of the vector
  //================
  //Usage example:
  //================
        // Data set up
                                std::vector<int> result;
                                std::vector<ConPtr> vcA, vcB;
                                ContainerNeuronPtr neuronContainerPtr(new
      Container<Neuron>());
                                ConContainerPtr conContainerPtr(new
      ConContainer());
                                ConPtr ptC;
                                NeuronPtr ptN;
                                int ids[]= 10, 20, 30;
                                double weights[] = 1.13, 2.22, 3.33 ;
                                for (int i=0; i<=2 ; i++) /
      / Let's create a vector with three neurons
                                        ptN.reset(new Neuron(ids[i]));
                                        neuronContainerPtr->push_back(ptN);
                                
        // Test
                                for (int i=0; i<=2 ; i++) /
      / and a vector with three connections
                                        result.push_back(conContainerPtr->numOfCo
      ns()); // Append numOfCons to result, create new Con and push_back into
      conContainer
                                        ptC.reset(new Con(neuronContainerPtr->l
      oad().at(i), weights[i]));
                                        conContainerPtr->push_back(ptC);
                                
        // Now, result contains a numeric vector with values 0, 1, 2, and 3.
See also
Container::size (alias)
Definition at line 52 of file ConContainer.cpp.
References Container< Con >::size().
Referenced by getId().
  return size();
ConContainerPtr ConContainer::select (std::vector< int > nIds)
Selects the specified elements from the vecCom object.
Provides a convenient way of selecting some Con objects from the collection field of the ConContainer object.
Parameters
vFrom An std::vector<int> with the Ids of the connections to select.
        //================
        //Usage example:
        //================
        // Data set up
                std::vector<int> result;
                std::vector<NeuronPtr> neuronContainer;
                ConContainerPtr conContainerPtr(new ConContainer());
                ConPtr ptC;
                NeuronPtr ptN;
                int ids[]= 11, 10, 9, 3, 4, 5, 6, 7, 8, 2, 1;
                double weights[]=11.32, 1.26, 2.14, 3.16, 4.14, 5.19, 6.18, 7.16
      , 8.14, 9.12, 10.31;
                std::vector<double> nWeights;
                for (int i=0; i<11; i++)
                        nWeights.push_back(weights[i]);
                
                for (int i=0; i<nWeights.size() ; i++) /
      / Let's create a vector with three neurons
                        ptN.reset(new Neuron(ids[i]));
                        neuronContainer.push_back(ptN);
                
                conContainerPtr->buildAndAppend(neuronContainer, nWeights);
                // Test
                std::vector<int> toSelect;
                toSelect.push_back(1);
                toSelect.push_back(3);
                toSelect.push_back(5);
                toSelect.push_back(7);
                ConContainerPtr vSelect (conContainerPtr->select(toSelect));
      
                result=vSelect->getId();
                // Now, result is a numeric vector with the values 1, 3, 5 and 7.
      
See also
erase and the unit test files, e.g. runit.Cpp.ConContainer.R, for further examples.
Definition at line 505 of file ConContainer.cpp.
References Container< Con >::begin(), Container< Con >::end(), and Container< Con >::size().
Referenced by setWeight().
  ConContainerPtr result(new ConContainer);
  result->reserve(size());
  sort(begin(), end(), CompareId());
  sort(nIds.begin(), nIds.end());
  set_intersection(begin(), end(), nIds.begin(), nIds.end(),
      std::back_inserter(*result), CompareId());
  return result;
bool ConContainer::setFrom (NeuronContainer neuronContainer)
Setter of the from fields of the Con objects related to ConContainer.
This function provides a convenient way of getting the values of the weight field of those Con object pointed to by the smart pointer stored in the ConContainer object.
Parameters
vFrom An std::vector<NeuronPtr> with the pointers to be set in the from fields of the ConContainer object.
Returns
true if not exception is thrown
        //================
        //Usage example:
        //================
        // Data set up
                std::vector<int> result;
                ContainerNeuronPtr neuronContainerPtr(new
      Container<Neuron>());
                ConContainerPtr conContainerPtr(new ConContainer());
                ConPtr ptC;
                NeuronPtr ptN;
                int ids[]= 10, 20, 30;
                double weights[] = 1.13, 2.22, 3.33 ;
                for (int i=0; i<=2 ; i++) // Let's
      create a vector with three neurons
                        ptN.reset(new Neuron(ids[i]));
                        neuronContainerPtr->push_back(ptN);
                
                for (int i=0; i<=2 ; i++) // and a
      vector with three connections
                        ptC.reset(new Con());
                        conContainerPtr->push_back(ptC);
                
        // Test
                conContainerPtr->setFrom(neuronContainerPtr->load()) ;
                conContainerPtr->show();
                result=conContainerPtr->getId();
        // Now result is a vector that contains the values 10, 20 and 30.
See also
getFrom and the unit test files, e.g. runit.Cpp.ConContainer.R, for further examples.
Definition at line 333 of file ConContainer.cpp.
References Container< T >::begin(), Container< T >::empty(), Container< Con >::size(), and Container< T >::size().
  BEGIN_RCPP
  if (neuronContainer.empty())
     throw std::range_error("[ C++ ConContainer::setFrom]: Error, w is empty");
      
  if (neuronContainer.size() != size())
    
      throw std::range_error(
          "[C++ ConContainer::setFrom]: Error, neuronContainer.size() != collecti
      on.size()");
    
  std::vector<NeuronPtr>::iterator itrNeuron = neuronContainer.begin();
  foreach(ConPtr itr , *this)
    
      itr->setFrom(*itrNeuron);
      itrNeuron++;
    
  return true;
END_RCPP
bool ConContainer::setWeight (std::vector< double > nWeights, std::vector< int > nIds)
Setter of the weights of the specified elements from the ConContainer object.
Provides a convenient way of setting the weights of some Con objects from the collection field of the ConContainer object.
Parameters
nWeights A numeric (double) vector with the weights to be set in the Con objects contained in the ConContainer object.
vFrom An std::vector<int> with the Ids of the connections to select
Returns
true in case no exception is thrown
        //================
        //Usage example:
        //================
        // Data set up
                std::vector<double> result;
                        std::vector<NeuronPtr> neuronContainer;
                        ConContainerPtr conContainerPtr(new ConContainer());
                        ConPtr ptC;
                        NeuronPtr ptN;
                        int ids[]= 11, 10, 9, 3, 4, 5, 6, 7, 8, 2, 1;
                        double weights[]=11.32, 1.26, 2.14, 3.16, 4.14, 5.19, 6.
      18, 7.16, 8.14, 9.12, 10.31;
                        std::vector<double> nWeights;
                        for (int i=0; i<11; i++)
                        nWeights.push_back(weights[i]);
                        
                        for (int i=0; i<nWeights.size() ; i++) /
      / Let's create a vector with three neurons
                        ptN.reset(new Neuron(ids[i]));
                        neuronContainer.push_back(ptN);
                        
                        conContainerPtr->buildAndAppend(neuronContainer, nWeights
      );
                        std::vector<int> toSelect;
                        std::vector<double> vNewWeights;
                        toSelect.push_back(1);
                        toSelect.push_back(3);
                        toSelect.push_back(5);
                        toSelect.push_back(7);
                        vNewWeights.push_back(1000.1);
                        vNewWeights.push_back(3000.3);
                        vNewWeights.push_back(5000.5);
                        vNewWeights.push_back(7000.7);
                        conContainerPtr->setWeight(vNewWeights, toSelect);
        // Test
                        result = conContainerPtr->getWeight();
                        return wrap(result);
        // Now, result is a numeric vector with the values 1000.10, 9.12, 3000.3
      0, 4.14, 5000.50, 6.18, 7000.70, 8.14, 2.14, 1.26 and 11.32 .
See also
getWeigth and the unit test files, e.g. runit.Cpp.ConContainer.R, for further examples.
Definition at line 627 of file ConContainer.cpp.
References select().
BEGIN_RCPP return select(nIds)->setWeight(nWeights);
END_RCPP
bool ConContainer::setWeight (std::vector< double > nWeights)
Setter of the weight field of the Con objects related to ConContainer.
This function provides a convenient way of setting the values of the weight field of those Con objects pointed to by the smart pointer stored in the ConContainer object.
Parameters
nWeights A numeric (double) vector with the weights to be set in the Con objects contained in the ConContainer object.
Returns
true in case no exception is thrown
        //================
        //Usage example:
        //================
        // Data set up
                std::vector<double> result;
                        int ids[]= 1, 2, 3;
                        double weights[] = 12.3, 1.2, 2.1 ;
                        ConContainer conContainer;
                        std::vector<NeuronPtr> neuronContainer;
                        std::vector<double> nWeights;
                        NeuronPtr ptNeuron;
                        for (int i=0; i<=2; i++)
                        ptNeuron.reset(new Neuron(ids[1]));
                        neuronContainer.push_back(ptNeuron);
                        nWeights.push_back(0); /
      / weights are set to 0
                        
                        conContainer.buildAndAppend(neuronContainer, nWeights);
                        conContainer.show();
                        for (int i=0; i<=2; i++)
                                nWeights.at(i)=weights[i];
                        
        // Test
                        conContainer.setWeight(nWeights); /
      / weights are set to 12.3, 1.2 and 2.1
                        result=conContainer.getWeight();
        // Now result is a vector that contains the values 12.3, 1.2 and 2.1 .
See also
getWeight and the unit test files, e.g. runit.Cpp.ConContainer.R, for further examples.
Definition at line 270 of file ConContainer.cpp.
References Container< Con >::size().
  BEGIN_RCPP
  if (nWeights.empty())
     throw std::range_error("[ C++ ConContainer::setWeight]: Error, nWeights is
      empty");
  if (nWeights.size() != size())
    
      throw std::range_error(
          "[C++ ConContainer::setWeight]: Error, nWeights.size() != collection.si
      ze()");
    
  std::vector<double>::iterator itrWeight = nWeights.begin();
  foreach (ConPtr itr, *this)
    
      itr->setWeight(*itrWeight);
      itrWeight++;
    
  return true;
END_RCPP
bool ConContainer::validate () [virtual]
Object validator.
This method checks the object for internal coherence. A try / catch mechanism exits normal execution and returns control to the R terminal in case the contents of the ConContainer object are identified as corrupted.
Returns
true in case the checks are Ok.
Exceptions
An std::range error if weight or from are not finite.
See also
The unit test files, e.g., runit.Cpp.ConContainer.R, for usage examples.
Implements Container< Con >.
Definition at line 645 of file ConContainer.cpp.
References getId().
  BEGIN_RCPP
  std::vector<int>::iterator itr;
  std::vector<int> vIds = getId();
  sort(vIds.begin(), vIds.end());
  itr = adjacent_find(vIds.begin(), vIds.end());
  if (itr != vIds.end())
    throw std::range_error(
        "[C++ ConContainer::validate]: Error, duplicated Id.");
  Container<Con>::validate();
  return (true);
END_RCPP;
The documentation for this class was generated from the following files:
pkg/AMORE/src/old/ConContainer.h
pkg/AMORE/src/old/ConContainer.cpp