MLPfactory Class Reference
class MLPfactory -
#include <MLPfactory.h>
Protected Member Functions
ConPtr makeCon (Neuron &neuron, double weight)
ConContainerPtr makeConContainer ()
virtual ActivationFunctionPtr makeActivationFunction (NeuronPtr neuronPtr)=0
PredictBehaviorPtr makePredictBehavior (NeuronPtr neuronPtr)
NeuronPtr makeNeuron (Handler Id)
NeuronPtr makeNeuron (Handler Id, NeuronIteratorPtr neuronIteratorPtr, double totalAmountOfParameters)
LayerPtr makeLayer ()
LayerContainerPtr makeLayerContainer ()
NeuralNetworkPtr makeNeuralNetwork (NeuralFactory &neuralFactory)
NeuralCreatorPtr makeNeuralCreator ()
Detailed Description
class MLPfactory -
Definition at line 5 of file MLPfactory.h.
Member Function Documentation
virtual ActivationFunctionPtr MLPfactory::makeActivationFunction (NeuronPtr neuronPtr) [protected, pure virtual]
Implements NeuralFactory.
Implemented in ArcTanFactory, CosineFactory, ElliotFactory, ExponentialFactory, GaussFactory, IdentityFactory, LogisticFactory, ReciprocalFactory, SineFactory, SquareFactory, TanhFactory, and ThresholdFactory.
Referenced by makeNeuron().
ConPtr MLPfactory::makeCon (Neuron & neuron, double weight) [protected, virtual]
Implements NeuralFactory.
Definition at line 30 of file MLPfactory.cpp.
Referenced by makeNeuron().
  ConPtr conPtr(new Con(neuron, weight));
  return conPtr;
ConContainerPtr MLPfactory::makeConContainer () [protected, virtual]
Implements NeuralFactory.
Definition at line 37 of file MLPfactory.cpp.
  ConContainerPtr conContainerPtr(new SimpleContainer<ConPtr>);
  return conContainerPtr;
LayerPtr MLPfactory::makeLayer () [protected, virtual]
Implements NeuralFactory.
Definition at line 84 of file MLPfactory.cpp.
Referenced by makeLayerContainer().
  LayerPtr layerPtr(new SimpleContainer<NeuronPtr>);
  return layerPtr;
LayerContainerPtr MLPfactory::makeLayerContainer () [protected, virtual]
Implements NeuralFactory.
Definition at line 92 of file MLPfactory.cpp.
References makeLayer().
  LayerContainerPtr layerContainerPtr(new SimpleContainer<LayerPtr>);
  layerContainerPtr->push_back(makeLayer());
  return layerContainerPtr;
NeuralCreatorPtr MLPfactory::makeNeuralCreator () [protected, virtual]
Implements NeuralFactory.
Definition at line 109 of file MLPfactory.cpp.
  NeuralCreatorPtr neuralCreatorPtr(new SimpleNeuralCreator);
  return neuralCreatorPtr;
NeuralNetworkPtr MLPfactory::makeNeuralNetwork (NeuralFactory & neuralFactory) [protected, virtual]
Implements NeuralFactory.
Definition at line 101 of file MLPfactory.cpp.
  NeuralNetworkPtr neuralNetworkPtr(new SimpleNetwork(neuralFactory));
  return neuralNetworkPtr;
NeuronPtr MLPfactory::makeNeuron (Handler Id) [protected, virtual]
Implements NeuralFactory.
Definition at line 52 of file MLPfactory.cpp.
References makeActivationFunction(), and makePredictBehavior().
Referenced by makeNeuron().
  NeuronPtr neuronPtr(new SimpleNeuron(*this));
  neuronPtr->setId(Id);
  neuronPtr->setPredictBehavior(makePredictBehavior(neuronPtr));
  neuronPtr->setActivationFunction(makeActivationFunction(neuronPtr));
  return neuronPtr;
NeuronPtr MLPfactory::makeNeuron (Handler Id, NeuronIteratorPtr neuronIteratorPtr, double totalAmountOfParameters) [protected, virtual]
Implements NeuralFactory.
Definition at line 62 of file MLPfactory.cpp.
References MLPbehavior::d_bias, makeCon(), and makeNeuron().
  RNGScope scope;
  NeuronPtr neuronPtr(makeNeuron(Id));
  double extreme = sqrt(3 / totalAmountOfParameters);
  double weight;
  for (neuronIteratorPtr->first(); !neuronIteratorPtr->isDone(); neuronIteratorPt
      r->next())
    
      weight =as<double>(runif(1, -extreme, extreme));
      neuronPtr->addCon(makeCon(*neuronIteratorPtr->currentItem(), weight));
    
  MLPbehavior* mlpBehavior = dynamic_cast<MLPbehavior*>(neuronPtr->d_predictBehav
      ior.get()) ;
  mlpBehavior->d_bias=as<double>(runif(1, -extreme, extreme));
return neuronPtr;
PredictBehaviorPtr MLPfactory::makePredictBehavior (NeuronPtr neuronPtr) [protected, virtual]
Implements NeuralFactory.
Definition at line 45 of file MLPfactory.cpp.
Referenced by makeNeuron().
  PredictBehaviorPtr predictBehaviorPtr(new MLPbehavior(neuronPtr));
  return predictBehaviorPtr;
The documentation for this class was generated from the following files:
/Users/mcasl/pc-ule/Trabajo/investigacion/AMORE/AMORE-WC/AMORE-WC/pkg/AMORE/src/classHeaders/MLPfactory.h
/Users/mcasl/pc-ule/Trabajo/investigacion/AMORE/AMORE-WC/AMORE-WC/pkg/AMORE/src/MLPfactory.cpp