NeuralFactory Class Reference
class NeuralFactory -
#include <NeuralFactory.h>
Public Member Functions
virtual ConPtr makeCon (Neuron &neuron, double weight)=0
virtual ConContainerPtr makeConContainer ()=0
virtual ActivationFunctionPtr makeActivationFunction (NeuronPtr neuronPtr)=0
virtual PredictBehaviorPtr makePredictBehavior (NeuronPtr neuronPtr)=0
virtual NeuronPtr makeNeuron (Handler Id)=0
virtual NeuronPtr makeNeuron (Handler Id, NeuronIteratorPtr neuronIteratorPtr, double totalAmountOfParameters)=0
virtual LayerPtr makeLayer ()=0
virtual LayerContainerPtr makeLayerContainer ()=0
virtual NeuralNetworkPtr makeNeuralNetwork (NeuralFactory &neuralFactory)=0
virtual NeuralCreatorPtr makeNeuralCreator ()=0
Detailed Description
class NeuralFactory -
Definition at line 4 of file NeuralFactory.h.
Member Function Documentation
virtual ActivationFunctionPtr NeuralFactory::makeActivationFunction (NeuronPtr neuronPtr) [pure virtual]
Implemented in ArcTanFactory, CosineFactory, ElliotFactory, ExponentialFactory, GaussFactory, IdentityFactory, LogisticFactory, MLPfactory, RadialBasisFactory, RBFfactory, ReciprocalFactory, SineFactory, SquareFactory, TanhFactory, and ThresholdFactory.
virtual ConPtr NeuralFactory::makeCon (Neuron & neuron, double weight) [pure virtual]
Implemented in MLPfactory.
virtual ConContainerPtr NeuralFactory::makeConContainer () [pure virtual]
Implemented in MLPfactory, and RBFfactory.
Referenced by Neuron::Neuron().
virtual LayerPtr NeuralFactory::makeLayer () [pure virtual]
Implemented in MLPfactory, and RBFfactory.
Referenced by SimpleNeuralCreator::createFeedForwardNetwork(), and NeuralNetwork::NeuralNetwork().
virtual LayerContainerPtr NeuralFactory::makeLayerContainer () [pure virtual]
Implemented in MLPfactory, and RBFfactory.
Referenced by NeuralNetwork::NeuralNetwork().
virtual NeuralCreatorPtr NeuralFactory::makeNeuralCreator () [pure virtual]
Implemented in MLPfactory, and RBFfactory.
virtual NeuralNetworkPtr NeuralFactory::makeNeuralNetwork (NeuralFactory & neuralFactory) [pure virtual]
Implemented in MLPfactory, and RBFfactory.
Referenced by SimpleNeuralCreator::createFeedForwardNetwork().
virtual NeuronPtr NeuralFactory::makeNeuron (Handler Id) [pure virtual]
Implemented in MLPfactory, and RBFfactory.
Referenced by SimpleNeuralCreator::createFeedForwardNetwork().
virtual NeuronPtr NeuralFactory::makeNeuron (Handler Id, NeuronIteratorPtr neuronIteratorPtr, double totalAmountOfParameters) [pure virtual]
Implemented in MLPfactory, and RBFfactory.
virtual PredictBehaviorPtr NeuralFactory::makePredictBehavior (NeuronPtr neuronPtr) [pure virtual]
Implemented in MLPfactory.
The documentation for this class was generated from the following file:
/Users/mcasl/pc-ule/Trabajo/investigacion/AMORE/AMORE-WC/AMORE-WC/pkg/AMORE/src/classHeaders/NeuralFactory.h