PredictBehavior Class Reference
class PredictBehavior -
#include <PredictBehavior.h>
Public Member Functions
virtual void singlePatternForwardAction ()=0
virtual void show ()=0
Protected Member Functions
PredictBehavior (NeuronPtr neuronPtr)
double useActivationFunctionf0 ()
double useActivationFunctionf1 ()
ConIteratorPtr getConIterator ()
void setOutput (double output)
void setOutputDerivative (double outputDerivative)
void setInducedLocalField (double inducedLocalField)
Protected Attributes
NeuronWeakPtr d_neuron
Detailed Description
class PredictBehavior -
Definition at line 4 of file PredictBehavior.h.
Constructor & Destructor Documentation
PredictBehavior::PredictBehavior (NeuronPtr neuronPtr) [protected]
Definition at line 14 of file PredictBehavior.cpp.
                                                    :
  d_neuron(neuronPtr)
Member Function Documentation
ConIteratorPtr PredictBehavior::getConIterator () [protected]
Definition at line 36 of file PredictBehavior.cpp.
References d_neuron.
Referenced by MLPbehavior::singlePatternForwardAction().
  NeuronPtr neuronPtr(d_neuron.lock()) ;
  return neuronPtr->getConIterator();
void PredictBehavior::setInducedLocalField (double inducedLocalField) [protected]
Definition at line 59 of file PredictBehavior.cpp.
References d_neuron.
Referenced by MLPbehavior::singlePatternForwardAction().
  NeuronPtr neuronPtr(d_neuron.lock()) ;
  return neuronPtr->setInducedLocalField(inducedLocalField);
void PredictBehavior::setOutput (double output) [protected]
Definition at line 43 of file PredictBehavior.cpp.
References d_neuron.
Referenced by MLPbehavior::singlePatternForwardAction().
  NeuronPtr neuronPtr(d_neuron.lock()) ;
  return neuronPtr->setOutput(output);
void PredictBehavior::setOutputDerivative (double outputDerivative) [protected]
Definition at line 51 of file PredictBehavior.cpp.
References d_neuron.
Referenced by MLPbehavior::singlePatternForwardAction().
  NeuronPtr neuronPtr(d_neuron.lock()) ;
  return neuronPtr->setOutputDerivative(outputDerivative);
virtual void PredictBehavior::show () [pure virtual]
Implemented in MLPbehavior, and RBFbehavior.
virtual void PredictBehavior::singlePatternForwardAction () [pure virtual]
Implemented in MLPbehavior, and RBFbehavior.
double PredictBehavior::useActivationFunctionf0 () [protected]
Definition at line 20 of file PredictBehavior.cpp.
References d_neuron.
Referenced by MLPbehavior::singlePatternForwardAction().
  NeuronPtr neuronPtr(d_neuron.lock()) ;
  return neuronPtr->useActivationFunctionf0();
double PredictBehavior::useActivationFunctionf1 () [protected]
Definition at line 28 of file PredictBehavior.cpp.
References d_neuron.
Referenced by MLPbehavior::singlePatternForwardAction().
  NeuronPtr neuronPtr(d_neuron.lock()) ;
  return neuronPtr->useActivationFunctionf1();
Member Data Documentation
NeuronWeakPtr PredictBehavior::d_neuron [protected]
Definition at line 7 of file PredictBehavior.h.
Referenced by getConIterator(), setInducedLocalField(), setOutput(), setOutputDerivative(), useActivationFunctionf0(), and useActivationFunctionf1().
The documentation for this class was generated from the following files:
/Users/mcasl/pc-ule/Trabajo/investigacion/AMORE/AMORE-WC/AMORE-WC/pkg/AMORE/src/classHeaders/PredictBehavior.h
/Users/mcasl/pc-ule/Trabajo/investigacion/AMORE/AMORE-WC/AMORE-WC/pkg/AMORE/src/PredictBehavior.cpp