ActivationFunction Class Reference
class ActivationFunction -
#include <ActivationFunction.h>
Public Member Functions
virtual double f0 ()=0
virtual double f1 ()=0
double getInducedLocalField ()
void setPredictBehavior (PredictBehaviorPtr predictBehaviorPtr)
Protected Attributes
PredictBehaviorWeakPtr d_predictBehavior
Detailed Description
class ActivationFunction -
Definition at line 4 of file ActivationFunction.h.
Member Function Documentation
virtual double ActivationFunction::f0 () [pure virtual]
Implemented in ArcTan, Cosine, Elliot, Exponential, Gauss, Identity, Logistic, RadialBasis, Reciprocal, Sine, Square, Tanh, and Threshold.
virtual double ActivationFunction::f1 () [pure virtual]
Implemented in ArcTan, Cosine, Elliot, Exponential, Gauss, Identity, Logistic, RadialBasis, Reciprocal, Sine, Square, Tanh, and Threshold.
double ActivationFunction::getInducedLocalField ()
Definition at line 12 of file ActivationFunction.cpp.
References d_predictBehavior.
Referenced by Tanh::f0(), Identity::f0(), and Tanh::f1().
                                                 
  PredictBehaviorPtr predictBehaviorPtr (d_predictBehavior.lock());
      return predictBehaviorPtr->getInducedLocalField();
void ActivationFunction::setPredictBehavior (PredictBehaviorPtr predictBehaviorPtr)
Definition at line 18 of file ActivationFunction.cpp.
References d_predictBehavior.
                                                                                 
       
   d_predictBehavior = predictBehaviorPtr;
Member Data Documentation
PredictBehaviorWeakPtr ActivationFunction::d_predictBehavior [protected]
Definition at line 7 of file ActivationFunction.h.
Referenced by getInducedLocalField(), and setPredictBehavior().
The documentation for this class was generated from the following files:
pkg/AMORE/src/dia/ActivationFunction.h
pkg/AMORE/src/ActivationFunction.cpp