SimpleNeuron Class Reference
class SimpleNeuron -
#include <SimpleNeuron.h>
Public Member Functions
SimpleNeuron (NeuralFactory &neuralFactory)
Private Member Functions
double getInducedLocalField ()
void setInducedLocalField (double inducedLocalField)
double getOutput ()
void setOutput (double output)
Handler getId ()
void setId (Handler Id)
ConIteratorPtr getConIterator ()
void addCon (ConPtr conPtr)
void setActivationFunction (ActivationFunctionPtr activationFunctionPtr)
void setPredictBehavior (PredictBehaviorPtr predictBehaviorPtr)
double useActivationFunctionf0 ()
void predict ()
void show ()
bool validate ()
Detailed Description
class SimpleNeuron -
Definition at line 5 of file SimpleNeuron.h.
Constructor & Destructor Documentation
SimpleNeuron::SimpleNeuron (NeuralFactory & neuralFactory)
Definition at line 10 of file SimpleNeuron.cpp.
                                                       :
  Neuron(neuralFactory)
Member Function Documentation
void SimpleNeuron::addCon (ConPtr conPtr) [private, virtual]
Implements Neuron.
Definition at line 59 of file SimpleNeuron.cpp.
References Neuron::d_nCons.
  d_nCons->push_back(conPtr) ;
ConIteratorPtr SimpleNeuron::getConIterator () [private, virtual]
Implements Neuron.
Definition at line 53 of file SimpleNeuron.cpp.
References Neuron::d_nCons.
  return d_nCons->createIterator();
Handler SimpleNeuron::getId () [private, virtual]
Implements Neuron.
Definition at line 41 of file SimpleNeuron.cpp.
References Neuron::d_Id.
Referenced by show(), and validate().
  return d_Id;
double SimpleNeuron::getInducedLocalField () [private, virtual]
Implements Neuron.
Definition at line 17 of file SimpleNeuron.cpp.
References Neuron::d_inducedLocalField.
  return d_inducedLocalField;
double SimpleNeuron::getOutput () [private, virtual]
Implements Neuron.
Definition at line 29 of file SimpleNeuron.cpp.
References Neuron::d_output.
  return d_output;
void SimpleNeuron::predict () [private, virtual]
Implements Neuron.
Definition at line 83 of file SimpleNeuron.cpp.
References Neuron::d_predictBehavior.
  d_predictBehavior->predict();
void SimpleNeuron::setActivationFunction (ActivationFunctionPtr activationFunctionPtr) [private, virtual]
Implements Neuron.
Definition at line 65 of file SimpleNeuron.cpp.
References Neuron::d_activationFunction.
  d_activationFunction = activationFunctionPtr;
void SimpleNeuron::setId (Handler Id) [private, virtual]
Implements Neuron.
Definition at line 47 of file SimpleNeuron.cpp.
References Neuron::d_Id.
  d_Id = Id;
void SimpleNeuron::setInducedLocalField (double inducedLocalField) [private, virtual]
Implements Neuron.
Definition at line 23 of file SimpleNeuron.cpp.
References Neuron::d_inducedLocalField.
  d_inducedLocalField = inducedLocalField;
void SimpleNeuron::setOutput (double output) [private, virtual]
Implements Neuron.
Definition at line 35 of file SimpleNeuron.cpp.
References Neuron::d_output.
  d_output = output;
void SimpleNeuron::setPredictBehavior (PredictBehaviorPtr predictBehaviorPtr) [private, virtual]
Implements Neuron.
Definition at line 71 of file SimpleNeuron.cpp.
References Neuron::d_predictBehavior.
  d_predictBehavior = predictBehaviorPtr;
void SimpleNeuron::show () [private, virtual]
Implements Neuron.
Definition at line 89 of file SimpleNeuron.cpp.
References Neuron::d_nCons, Neuron::d_output, Neuron::d_predictBehavior, and getId().
  int id = getId();
  Rprintf("------------------------");
  if (id == NA_INTEGER)
    
      Rprintf("Id: NA, Invalid neuron Id");
    
  else
    
      Rprintf("Id: %d", id);
    
  Rprintf("------------------------");
  d_predictBehavior->show();
  Rprintf("output: %lf", d_output);
  Rprintf("------------------------");
  if (d_nCons->size() == 0)
    
      Rprintf("No connections defined");
    
  else
    
      d_nCons->show();
    
  Rprintf("------------------------");
double SimpleNeuron::useActivationFunctionf0 () [private, virtual]
Implements Neuron.
Definition at line 77 of file SimpleNeuron.cpp.
References Neuron::d_activationFunction.
  return d_activationFunction->f0();
bool SimpleNeuron::validate () [private, virtual]
Implements Neuron.
Definition at line 118 of file SimpleNeuron.cpp.
References getId().
  BEGIN_RCPP
  if (getId() == NA_INTEGER) throw std::range_error("[C++ SimpleNeuron::validate
      ]: Error, Id is NA.");
  // nCons.validate();
  return (TRUE);
END_RCPP
The documentation for this class was generated from the following files:
pkg/AMORE/src/dia/SimpleNeuron.h
pkg/AMORE/src/SimpleNeuron.cpp