Con Class Reference
class Con -
#include <Con.h>
Public Member Functions
Con (Neuron &neuron)
Constructor.
Con (Neuron &neuron, double weight)
Constructor.
Handler Id ()
A getter of the Id of the Neuron pointed by the from field.
Neuron & getNeuron ()
from field accessor.
void setNeuron (Neuron &neuron)
double getWeight ()
weight field accessor.
void setWeight (double weight)
weight field accessor.
void show ()
Pretty print of the Con information.
bool validate ()
Object validator.
Con ()
Default Constructor.
Con (NeuronPtr neuronPtr)
Constructor.
Con (NeuronPtr neuronPtr, double value)
Constructor.
~Con ()
Default Destructor.
NeuronPtr getFrom ()
from field accessor.
void setFrom (NeuronPtr neuronPtr)
from field accessor.
int getId ()
A getter of the Id of the Neuron pointed by the from field.
double getWeight ()
void setWeight (double value)
bool show ()
bool validate ()
Private Attributes
NeuronRef d_neuron
double d_weight
NeuronWeakPtr from
A smart pointer to the Neuron used as input during simulation or training.
double weight
A double variable that contains the weight of the connection.
Detailed Description
class Con -
A class to handle the information needed to describe an input connection.
The Con class provides a simple class for a connection described by a pair of values: a pointer to a Neuron object used as the from field and the weight used to propagate the value of that Neuron object.
Definition at line 3 of file Con.h.
Constructor & Destructor Documentation
Con::Con (Neuron & neuron)
Constructor.
Definition at line 19 of file Con.cpp.
                       :
  d_neuron(boost::ref(neuron)), d_weight(0)
Con::Con (Neuron & neuron, double weight)
Constructor.
Definition at line 30 of file Con.cpp.
                                      :
  d_neuron(boost::ref(neuron)), d_weight(weight)
Con::Con ()
Default Constructor.
Definition at line 17 of file Con.cpp.
         :
  weight(0), from()
Con::Con (NeuronPtr neuronPtr)
Constructor.
Definition at line 40 of file Con.cpp.
                            :
  from(neuronPtr), weight(0)
Con::Con (NeuronPtr neuronPtr, double value)
Constructor.
Definition at line 29 of file Con.cpp.
                                          :
  from(neuronPtr), weight(value)
Con::~Con ()
Default Destructor.
Definition at line 46 of file Con.cpp.
Member Function Documentation
NeuronPtr Con::getFrom ()
from field accessor.
This method allows access to the address stored in the private from field (a pointer to a Neuron object).*
Returns
A pointer to the Neuron object referred to by the from field.
        //================
        //Usage example:
        //================
        // Data set up
                        NeuronPtr ptShNeuron (new Neuron(1)); // Neuron
       Id is set 1
                        ConPtr ptShCon(new Con(ptShNeuron)); // from p
      oints to ptShNeuron and weight is set to 0
        // Test
                        ptShNeuron = ptShCon->getFrom() ;
                        int result = ptShNeuron->getId();
        // Now, result is equal to 1.
See also
getId and the unit test files, e.g., runit.Cpp.Con.R, for further examples.
Definition at line 71 of file Con.cpp.
References from.
  return (from.lock());
int Con::getId ()
A getter of the Id of the Neuron pointed by the from field.
This method gets the Id of the Neuron referred to by the from field
Returns
The value of the Id (an integer).
        //================
        //Usage example:
        //================
        // Data set up
                        NeuronPtr ptShNeuron (new Neuron(16)); // Neuron
       Id is set to 16
                        ConPtr ptShCon(new Con(ptShNeuron)); // from p
      oints to ptShNeuron and weight is set to 0
        // Test
                        int result = ptShCon->getId();
        // Now, result is equal to 16.
See also
getFrom, setFrom and the unit test files, e.g., runit.Cpp.Con.R, for further examples.
Definition at line 123 of file Con.cpp.
References from.
  if (from.use_count() > 0)
    
      NeuronPtr neuronPtr(from);
      return (neuronPtr->getId());
    
  else
    
      return (NA_INTEGER);
    
Neuron & Con::getNeuron ()
from field accessor.
This method allows access to the address stored in the private from field (a pointer to a Neuron object).*
Returns
A pointer to the Neuron object referred to by the from field.
        //================
        //Usage example:
        //================
        // Data set up
                        NeuronPtr ptShNeuron (new Neuron(1)); // Neuron
       Id is set 1
                        ConPtr ptShCon(new Con(ptShNeuron)); // from p
      oints to ptShNeuron and weight is set to 0
        // Test
                        ptShNeuron = ptShCon->getFrom() ;
                        int result = ptShNeuron->getId();
        // Now, result is equal to 1.
See also
getId and the unit test files, e.g., runit.Cpp.Con.R, for further examples.
Definition at line 56 of file Con.cpp.
References d_neuron.
  return d_neuron;
double Con::getWeight ()
weight field accessor.
This method allows access to the value stored in the private field weight
Returns
The value of weight (double)
  //================
  //Usage example:
  //================
  // Data set up
                        std::vector<double> result;
                        NeuronPtr ptShNeuron (new Neuron(16)); /
      / Neuron Id is set to 16
                        ConPtr ptShCon(new Con(ptShNeuron, 12.4)); // from poi
      nts to ptShNeuron and weight is set to 12.4
        // Test
                        result.push_back(ptShCon->getWeight());
                        ptShCon->setWeight(2.2);
                        result.push_back(ptShCon->getWeight());
        // Now, result is a numeric vector that contains the values 12.4 and 2.2
      .
See also
setWeight and the unit test files, e.g., runit.Cpp.Con.R, for further examples.
Definition at line 116 of file Con.cpp.
References d_weight.
Referenced by show(), and validate().
  return d_weight;
double Con::getWeight ()
int Con::Id ()
A getter of the Id of the Neuron pointed by the from field.
This method gets the Id of the Neuron referred to by the from field
Returns
The value of the Id (an integer).
      //================
      //Usage example:
      //================
      // Data set up
                      NeuronPtr ptShNeuron (new Neuron(16)); // Neuron I
      d is set to 16
                      ConPtr ptShCon(new Con(ptShNeuron)); // from poi
      nts to ptShNeuron and weight is set to 0
      // Test
                      int result = ptShCon->getId();
      // Now, result is equal to 16.
See also
getFrom, setFrom and the unit test files, e.g., runit.Cpp.Con.R, for further examples.
Definition at line 88 of file Con.cpp.
References d_neuron.
Referenced by show(), and validate().
  return d_neuron.get().getId();
void Con::setFrom (NeuronPtr neuronPtr)
from field accessor.
This method sets the value of the from field with the address used as parameter.
Parameters
f A pointer to the neuron that is to be inserted in the from field.
        //================
        //Usage example:
        //================
        // Data set up
                        NeuronPtr ptShNeuron (new Neuron(1)); // Neuron
       Id is set to 1
                        ConPtr ptShCon(new Con());
                        ptShCon->setFrom(ptShNeuron);
        // Test
                        ptShNeuron = ptShCon->getFrom() ;
                        int result = ptShNeuron->getId();
        // Now, result is equal to 1
See also
getFrom and getId contain usage examples. For further examples see the unit test files, e.g., runit.Cpp.Con.R
Definition at line 98 of file Con.cpp.
References from.
  from = neuronPtr;
void Con::setNeuron (Neuron & neuron)
Definition at line 63 of file Con.cpp.
References d_neuron.
  d_neuron=boost::ref(neuron);
void Con::setWeight (double value)
weight field accessor.
This method sets the value of the weight field.
Parameters
w The new value (double) to be set in the weight field.
  //================
  //Usage example:
  //================
  // Data set up
                        std::vector<double> result;
                        NeuronPtr ptShNeuron (new Neuron(16)); /
      / Neuron Id is set to 16
                        ConPtr ptShCon(new Con(ptShNeuron, 12.4)); // from poi
      nts to ptShNeuron and weight is set to 12.4
                        result.push_back(ptShCon->getWeight());
        // Test
                        ptShCon->setWeight(2.2);
                        result.push_back(ptShCon->getWeight());
        // Now, result is a numeric vector that contains the values 12.4 and 2.2
      .
See also
getWeight and the unit test files (e.g. runit.Cpp.Con.R)
Definition at line 123 of file Con.cpp.
References d_weight, and weight.
  d_weight=weight;
void Con::setWeight (double value)
bool Con::show ()
Pretty print of the Con information.
This method outputs in the R terminal the contents of the Con fields.
Returns
true in case everything works without throwing an exception
See also
setWeight and the unit test files, e.g., runit.Cpp.Con.R, for usage examples.
Definition at line 135 of file Con.cpp.
References getWeight(), and Id().
  int id = Id();
  if (id == NA_INTEGER)
    
      Rprintf("From: NAInvalid Connection ");
    
  else
    
      Rprintf("From:%d Weight= %lf ", id , getWeight());
    
bool Con::show ()
bool Con::validate ()
Object validator.
This method checks the object for internal coherence. A try / catch mechanism exits normal execution and returns control to the R terminal in case the contents of the Con object are identified as corrupted.
Returns
true in case the checks are Ok.
Exceptions
An std::range error if weight or from are not finite.
Definition at line 155 of file Con.cpp.
References getWeight(), and Id().
  BEGIN_RCPP
  if (! R_FINITE(getWeight())) throw std::range_error("weight is not finite.");
  if (Id() == NA_INTEGER)
    throw std::range_error("fromId is not finite.");
  return (true);
END_RCPP
bool Con::validate ()
Member Data Documentation
NeuronRef Con::d_neuron [private]
Definition at line 6 of file Con.h.
Referenced by getNeuron(), Id(), and setNeuron().
double Con::d_weight [private]
Definition at line 7 of file Con.h.
Referenced by getWeight(), and setWeight().
NeuronWeakPtr Con::from [private]
A smart pointer to the Neuron used as input during simulation or training.
The from field contains the address of the Neuron whose output will be used as input by the Neuron containing the Con object.
Definition at line 22 of file Con.h.
Referenced by getFrom(), getId(), and setFrom().
double Con::weight [private]
A double variable that contains the weight of the connection.
The weight field contains the factor by which the output value of the Neuron addressed by the from field is multiplied during simulation or training.
Definition at line 27 of file Con.h.
Referenced by setWeight().
The documentation for this class was generated from the following files:
pkg/AMORE/src/dia/Con.h
pkg/AMORE/src/old/Con.h
pkg/AMORE/src/Con.cpp
pkg/AMORE/src/old/Con.cpp