VecCon Class Reference
A vector of connections.
#include <VecCon.h>
Public Member Functions
int numOfCons ()
Size of the VecCon object.
std::vector< int > getId ()
Getter of the Id values of the vector of Cons.
bool buildAndAppend (std::vector< NeuronSharedPtr > vFrom, std::vector< double > vWeight)
Builds Con objects and appends them to collection.
std::vector< double > getWeight ()
Getter of the weight field of the Con objects related to VecCon.
std::vector< double > getWeight (std::vector< int > vFrom)
Getter of the weights of the specified elements from the vecCom object.
std::vector< NeuronSharedPtr > getFrom ()
Getter of the from field of the Con objects related to VecCon.
bool setWeight (std::vector< double > vWeight)
Setter of the weight field of the Con objects related to VecCon.
bool setWeight (std::vector< double > vWeight, std::vector< int > vFrom)
Setter of the weights of the specified elements from the VecCon object.
bool setFrom (std::vector< NeuronSharedPtr > vFrom)
Setter of the from fields of the Con objects related to VecCon.
void erase (std::vector< int > vFrom)
Erase the specified elements from the vecCom object.
VecConPtr select (std::vector< int > vFrom)
Selects the specified elements from the vecCom object.
bool validate ()
Object validator.
Detailed Description
A vector of connections.
The VecCon class provides a simple class for a vector of connections. It's named after the R equivalent Reference Class.
Definition at line 17 of file VecCon.h.
Member Function Documentation
bool VecCon::buildAndAppend (std::vector< NeuronSharedPtr > FROM, std::vector< double > WEIGHT)
Builds Con objects and appends them to collection.
This function provides a convenient way of populating a VecCon object by building and apending Con objects to collection.
Parameters
FROM A vector of smart pointers to the neurons to be used in the Con::from fields
WEIGHT A vector of values to be set in the Con::weight fields
        //================
        //Usage example:
        //================
        // Data set up
                std::vector<int> result;
                VecCon MyVecCon;
                std::vector<NeuronSharedPtr> vNeuron;
                std::vector<double> vWeight;
        // Test
                NeuronSharedPtr ptNeuron(new Neuron(11));
                vNeuron.push_back(ptNeuron);
                ptNeuron.reset(new Neuron(22));
                vNeuron.push_back(ptNeuron);
                ptNeuron.reset(new Neuron(33));
                vNeuron.push_back(ptNeuron);
                vWeight.push_back(12.3);
                vWeight.push_back(1.2);
                vWeight.push_back(2.1);
                MyVecCon.buildAndAppend(vNeuron, vWeight);
                result=MyVecCon.getId();
        // Now result is a vector that contains the values 11, 22 and 32.
See also
append and the unit test files, e.g. runit.Cpp.VecCon.R, for further examples.
Definition at line 130 of file VecCon.cpp.
References Container< Con >::collection.
                                                                                 
                 
        BEGIN_RCPP
        if (FROM.empty()) throw std::range_error("[VecCon::append]: Error, FROM
       is empty");
        if (FROM.size() != WEIGHT.size()) throw std::range_error("[VecCon::bui
      ldAndAppend]: Error, FROM.size() != WEIGHT.size()");
        collection.reserve(collection.size() + FROM.size());
        ConPtr ptCon;
        std::vector<double>::iterator itrWEIGHT = WEIGHT.begin();
        for(std::vector<NeuronSharedPtr>::iterator itrFROM=FROM.begin(); itrFR
      OM != FROM.end(); itrFROM++ , itrWEIGHT++)
                        ptCon.reset(new Con(*itrFROM, *itrWEIGHT));
                        collection.push_back(ptCon);
        
        return true;
        END_RCPP
void VecCon::erase (std::vector< int > vFrom)
Erase the specified elements from the vecCom object.
Provides a convenient way of removing some Con objects from the collection field of the VecCon object.
Parameters
vFrom An std::vector<int> with the Ids of the connections to remove.
        //================
        //Usage example:
        //================
        // Data set up
                        std::vector<int> result;
                        std::vector<NeuronSharedPtr> vNeuron;
                        VecConPtr ptShvCon(new VecCon());
                        VecConPtr vErased;
                        ConPtr ptC;
                        NeuronSharedPtr ptN;
                        int ids[]= 11, 10, 9, 3, 4, 5, 6, 7, 8, 2, 1;
                        std::vector<double> vWeight;
                        vWeight.push_back(11.32);
                        vWeight.push_back(1.26);
                        vWeight.push_back(2.14);
                        vWeight.push_back(3.16);
                        vWeight.push_back(4.14);
                        vWeight.push_back(5.19);
                        vWeight.push_back(6.18);
                        vWeight.push_back(7.16);
                        vWeight.push_back(8.14);
                        vWeight.push_back(9.12);
                        vWeight.push_back(10.31);
                        for (int i=0; i<vWeight.size() ; i++) /
      / Let's create a vector with three neurons
                                ptN.reset(new Neuron(ids[i]));
                                vNeuron.push_back(ptN);
                        
                        ptShvCon->buildAndAppend(vNeuron, vWeight);
                        // Test
                        std::vector<int> toRemove;
                        toRemove.push_back(1);
                        toRemove.push_back(3);
                        toRemove.push_back(5);
                        toRemove.push_back(7);
                        ptShvCon->erase(toRemove);
                        ptShvCon->show();
                        result=ptShvCon->getId();
                // The output at the R terminal would display :
                //
                // From: 2 Weight= 9.120000
                // From: 4 Weight= 4.140000
                // From: 6 Weight= 6.180000
                // From: 8 Weight= 8.140000
                // From: 9 Weight= 2.140000
                // From: 10 Weight= 1.260000
                // From: 11 Weight= 11.320000
See also
select and the unit test files, e.g. runit.Cpp.VecCon.R, for further examples.
Definition at line 445 of file VecCon.cpp.
References Container< Con >::collection.
                                         
        std::vector<ConPtr>::iterator itr;
        sort (collection.begin(), collection.end(), CompareId());
        sort (vFrom.begin(), vFrom.end());
        itr=set_difference (collection.begin(), collection.end(), vFrom.begin(), vFrom.end(
      ), collection.begin(), CompareId());
        collection.resize(itr-collection.begin());
std::vector< int > VecCon::getId ()
Getter of the Id values of the vector of Cons.
This function returns the Id's of the neurons referred to by the vector of Cons.
Returns
An std::vector<int> that contains the Ids
  //================
  //Usage example:
  //================
        // Data set up
                        Neuron N1, N2, N3;
                        VecCon MyVecCon;
                        std::vector<int> result;
                        N1.setId(10);
                        N2.setId(20);
                        N3.setId(30);
                        ConPtr ptCon(new Con(&N1, 1.13)); // Create
       new Con and initialize ptCon
                        MyVecCon.push_back(ptCon); /
      / push_back
                        ptCon.reset(new Con(&N2, 2.22)); // create
       new Con and assign to ptCon
                        MyVecCon.push_back(ptCon); /
      / push_back
                        ptCon.reset(new Con(&N3, 3.33)); // create
       new Con and assign to ptCon
                        MyVecCon.push_back(ptCon); /
      / push_back
        // Test
                        MyVecCon.show() ;
                        MyVecCon.validate();
                        result=MyVecCon.getId();
        // Now result is a vector that contains the values 10, 20 and 30.
See also
getWeight and the unit test files, e.g. runit.Cpp.VecCon.R, for further examples.
Definition at line 83 of file VecCon.cpp.
References Container< Con >::collection, and numOfCons().
Referenced by validate().
                                  
        std::vector<int> result;
        result.reserve(numOfCons());
        for(std::vector<ConPtr>::iterator itr = collection.begin(); itr !=
      collection.end(); itr++) result.push_back((*itr)->getId());
        return result;
std::vector< NeuronSharedPtr > VecCon::getFrom ()
Getter of the from field of the Con objects related to VecCon.
This function provides a convenient way of getting the values of the weight field of those Con object pointed to by the smart pointer stored in the VecCon object.
Returns
An std::vector<NeuronSharedPtr> with the pointer to the incoming neurons.
        //================
        //Usage example:
        //================
        // Data set up
                std::vector<double> result;
                int ids[]= 1, 2, 3;
                double weights[] = 12.3, 1.2, 2.1 ;
                VecCon MyVecCon;
                std::vector<NeuronSharedPtr> vNeuron;
                std::vector<double> vWeight;
                NeuronSharedPtr ptNeuron;
                        for (int i=0; i<=2; i++)
                                ptNeuron.reset(new Neuron(ids[i]));
                                vNeuron.push_back(ptNeuron);
                                vWeight.push_back(weights[i]);
                        
                        MyVecCon.buildAndAppend(vNeuron, vWeight);
                // Test
                        vNeuron=MyVecCon.getFrom();
                        for (int i=0; i<=2; i++)
                                result.push_back(vNeuron.at(i)->getId());
                        
        // Now result is a vector that contains the values 1, 2 and 3 .
See also
getId and the unit test files, e.g. runit.Cpp.VecCon.R, for further examples.
Definition at line 288 of file VecCon.cpp.
References Container< Con >::collection, and numOfCons().
                                                    
        std::vector<NeuronSharedPtr> result;
        result.reserve(numOfCons());
        for(std::vector<ConPtr>::iterator itr = collection.begin(); itr !=
      collection.end(); itr++)
                result.push_back((*itr)->getFrom());
        
        return result;
std::vector< double > VecCon::getWeight ()
Getter of the weight field of the Con objects related to VecCon.
This function provides a convenient way of getting the values of the weight field of those Con object pointed to by the smart pointer stored in the VecCon object.
Returns
A numeric (double) vector with the weights
        //================
        //Usage example:
        //================
        // Data set up
                std::vector<double> result;
                VecCon MyVecCon;
                std::vector<NeuronSharedPtr> vNeuron;
                std::vector<double> vWeight;
        // Test
                NeuronSharedPtr ptNeuron(new Neuron(11));
                vNeuron.push_back(ptNeuron);
                ptNeuron.reset(new Neuron(22));
                vNeuron.push_back(ptNeuron);
                ptNeuron.reset(new Neuron(33));
                vNeuron.push_back(ptNeuron);
                vWeight.push_back(12.3);
                vWeight.push_back(1.2);
                vWeight.push_back(2.1);
                MyVecCon.buildAndAppend(vNeuron, vWeight);
                result=MyVecCon.getWeight();
        // Now result is a vector that contains the values 12.3, 1.2 and 2.1 .
See also
getId and the unit test files, e.g. runit.Cpp.VecCon.R, for further examples.
Definition at line 185 of file VecCon.cpp.
References Container< Con >::collection, and numOfCons().
                                            
        std::vector<double> result;
        result.reserve(numOfCons());
        for(std::vector<ConPtr>::iterator itr = collection.begin(); itr !=
      collection.end(); itr++) result.push_back((*itr)->getWeight());
        return result;
std::vector< double > VecCon::getWeight (std::vector< int > vFrom)
Getter of the weights of the specified elements from the vecCom object.
Provides a convenient way of getting the weights of some Con objects from the collection field of the VecCon object.
Parameters
vFrom An std::vector<int> with the Ids of the connections to select
Returns
An std::vector<double> with the weights of the selected connections
        //================
        //Usage example:
        //================
        // Data set up
                std::vector<double> result;
                std::vector<NeuronSharedPtr> vNeuron;
                VecConPtr ptShvCon(new VecCon());
                ConPtr ptC;
                NeuronSharedPtr ptN;
                int ids[]= 11, 10, 9, 3, 4, 5, 6, 7, 8, 2, 1;
                double weights[]=11.32, 1.26, 2.14, 3.16, 4.14, 5.19, 6.18, 7.16
      , 8.14, 9.12, 10.31;
                std::vector<double> vWeight;
                for (int i=0; i<11; i++)
                        vWeight.push_back(weights[i]);
                
                for (int i=0; i<vWeight.size() ; i++) /
      / Let's create a vector with three neurons
                        ptN.reset(new Neuron(ids[i]));
                        vNeuron.push_back(ptN);
                
                ptShvCon->buildAndAppend(vNeuron, vWeight);
        // Test
                std::vector<int> toSelect;
                toSelect.push_back(1);
                toSelect.push_back(3);
                toSelect.push_back(5);
                toSelect.push_back(7);
                result=ptShvCon->getWeight(toSelect);
        // Now, result is a numeric vector with the values 10.31, 3.16, 5.19 an
      d 7.16.
See also
setWeigth and the unit test files, e.g. runit.Cpp.VecCon.R, for further examples.
Definition at line 558 of file VecCon.cpp.
References select().
                                                                        
        return select(vFrom)->getWeight();
int VecCon::numOfCons ()
Size of the VecCon object.
This function returns the size of the VecCon object, that is to say, the number of Con objects it contains.
Returns
The size of the vector
  //================
  //Usage example:
  //================
        // Data set up
                                std::vector<int> result;
                                std::vector<ConPtr> vcA, vcB;
                                ContainerneuronSharedPtr ptShvNeuron(new
      Container<Neuron>());
                                VecConPtr ptShvCon(new VecCon());
                                ConPtr ptC;
                                NeuronSharedPtr ptN;
                                int ids[]= 10, 20, 30;
                                double weights[] = 1.13, 2.22, 3.33 ;
                                for (int i=0; i<=2 ; i++) /
      / Let's create a vector with three neurons
                                        ptN.reset(new Neuron(ids[i]));
                                        ptShvNeuron->push_back(ptN);
                                
        // Test
                                for (int i=0; i<=2 ; i++) /
      / and a vector with three connections
                                        result.push_back(ptShvCon->numOfCons()); /
      / Append numOfCons to result, create new Con and push_back into MyVecCon
                                        ptC.reset(new Con(ptShvNeuron->load
      ().at(i), weights[i]));
                                        ptShvCon->push_back(ptC);
                                
        // Now, result contains a numeric vector with values 0, 1, 2, and 3.
See also
Container::size (alias)
Definition at line 42 of file VecCon.cpp.
References Container< Con >::collection.
Referenced by getId(), getFrom(), and getWeight().
                       
        return collection.size();
VecConPtr VecCon::select (std::vector< int > vFrom)
Selects the specified elements from the vecCom object.
Provides a convenient way of selecting some Con objects from the collection field of the VecCon object.
Parameters
vFrom An std::vector<int> with the Ids of the connections to select.
        //================
        //Usage example:
        //================
        // Data set up
                std::vector<int> result;
                std::vector<NeuronSharedPtr> vNeuron;
                VecConPtr ptShvCon(new VecCon());
                ConPtr ptC;
                NeuronSharedPtr ptN;
                int ids[]= 11, 10, 9, 3, 4, 5, 6, 7, 8, 2, 1;
                double weights[]=11.32, 1.26, 2.14, 3.16, 4.14, 5.19, 6.18, 7.16
      , 8.14, 9.12, 10.31;
                std::vector<double> vWeight;
                for (int i=0; i<11; i++)
                        vWeight.push_back(weights[i]);
                
                for (int i=0; i<vWeight.size() ; i++) /
      / Let's create a vector with three neurons
                        ptN.reset(new Neuron(ids[i]));
                        vNeuron.push_back(ptN);
                
                ptShvCon->buildAndAppend(vNeuron, vWeight);
                // Test
                std::vector<int> toSelect;
                toSelect.push_back(1);
                toSelect.push_back(3);
                toSelect.push_back(5);
                toSelect.push_back(7);
                VecConPtr vSelect (ptShvCon->select(toSelect));
                result=vSelect->getId();
                // Now, result is a numeric vector with the values 1, 3, 5 and 7.
      
See also
erase and the unit test files, e.g. runit.Cpp.VecCon.R, for further examples.
Definition at line 497 of file VecCon.cpp.
References Container< Con >::collection.
Referenced by getWeight(), and setWeight().
                                                     
        VecConPtr result(new VecCon);
        result->reserve(collection.size());
        sort (collection.begin(), collection.end(), CompareId());
        sort (vFrom.begin(), vFrom.end());
        set_intersection(collection.begin(), collection.end(), vFrom.begin(), vFrom.end(),
      back_inserter(result->collection) , CompareId());
        return result;
bool VecCon::setFrom (std::vector< NeuronSharedPtr > vFrom)
Setter of the from fields of the Con objects related to VecCon.
This function provides a convenient way of getting the values of the weight field of those Con object pointed to by the smart pointer stored in the VecCon object.
Parameters
vFrom An std::vector<NeuronSharedPtr> with the pointers to be set in the from fields of the VecCon object.
Returns
true if not exception is thrown
        //================
        //Usage example:
        //================
        // Data set up
                std::vector<int> result;
                ContainerneuronSharedPtr ptShvNeuron(new Container<Neuron>());
                VecConPtr ptShvCon(new VecCon());
                ConPtr ptC;
                NeuronSharedPtr ptN;
                int ids[]= 10, 20, 30;
                double weights[] = 1.13, 2.22, 3.33 ;
                for (int i=0; i<=2 ; i++) // Let's
      create a vector with three neurons
                        ptN.reset(new Neuron(ids[i]));
                        ptShvNeuron->push_back(ptN);
                
                for (int i=0; i<=2 ; i++) // and a
      vector with three connections
                        ptC.reset(new Con());
                        ptShvCon->push_back(ptC);
                
        // Test
                ptShvCon->setFrom(ptShvNeuron->load()) ;
                ptShvCon->show();
                result=ptShvCon->getId();
        // Now result is a vector that contains the values 10, 20 and 30.
See also
getFrom and the unit test files, e.g. runit.Cpp.VecCon.R, for further examples.
Definition at line 343 of file VecCon.cpp.
References Container< Con >::collection.
                                                                   
        BEGIN_RCPP
                if (vFrom.empty()) throw std::range_error("[ C++ VecCon::setFro
      mNeuron]: Error, w is empty");
                if (vFrom.size() != collection.size()) throw std::range_error("[C++
       VecCon::setFrom]: Error, w.size() != collection.size()");
                std::vector<NeuronSharedPtr>::iterator itrFrom = vFrom.begin();
                for(std::vector<ConPtr>::iterator itr = collection.begin(); it
      r != collection.end(); itr++, itrFrom++)
                        (*itr)->setFrom(*itrFrom);
                
                return true;
                END_RCPP
bool VecCon::setWeight (std::vector< double > vWeight, std::vector< int > vFrom)
Setter of the weights of the specified elements from the VecCon object.
Provides a convenient way of setting the weights of some Con objects from the collection field of the VecCon object.
Parameters
vWeight A numeric (double) vector with the weights to be set in the Con objects contained in the VecCon object.
vFrom An std::vector<int> with the Ids of the connections to select
Returns
true in case no exception is thrown
        //================
        //Usage example:
        //================
        // Data set up
                std::vector<double> result;
                        std::vector<NeuronSharedPtr> vNeuron;
                        VecConPtr ptShvCon(new VecCon());
                        ConPtr ptC;
                        NeuronSharedPtr ptN;
                        int ids[]= 11, 10, 9, 3, 4, 5, 6, 7, 8, 2, 1;
                        double weights[]=11.32, 1.26, 2.14, 3.16, 4.14, 5.19, 6.
      18, 7.16, 8.14, 9.12, 10.31;
                        std::vector<double> vWeight;
                        for (int i=0; i<11; i++)
                        vWeight.push_back(weights[i]);
                        
                        for (int i=0; i<vWeight.size() ; i++) /
      / Let's create a vector with three neurons
                        ptN.reset(new Neuron(ids[i]));
                        vNeuron.push_back(ptN);
                        
                        ptShvCon->buildAndAppend(vNeuron, vWeight);
                        std::vector<int> toSelect;
                        std::vector<double> vNewWeights;
                        toSelect.push_back(1);
                        toSelect.push_back(3);
                        toSelect.push_back(5);
                        toSelect.push_back(7);
                        vNewWeights.push_back(1000.1);
                        vNewWeights.push_back(3000.3);
                        vNewWeights.push_back(5000.5);
                        vNewWeights.push_back(7000.7);
                        ptShvCon->setWeight(vNewWeights, toSelect);
        // Test
                        result = ptShvCon->getWeight();
                        return wrap(result);
        // Now, result is a numeric vector with the values 1000.10, 9.12, 3000.3
      0, 4.14, 5000.50, 6.18, 7000.70, 8.14, 2.14, 1.26 and 11.32 .
See also
getWeigth and the unit test files, e.g. runit.Cpp.VecCon.R, for further examples.
Definition at line 620 of file VecCon.cpp.
References select().
                                                                                 
       
        BEGIN_RCPP
        return select(vFrom)->setWeight(vWeight);
        END_RCPP
bool VecCon::setWeight (std::vector< double > vWeight)
Setter of the weight field of the Con objects related to VecCon.
This function provides a convenient way of setting the values of the weight field of those Con objects pointed to by the smart pointer stored in the VecCon object.
Parameters
vWeight A numeric (double) vector with the weights to be set in the Con objects contained in the VecCon object.
Returns
true in case no exception is thrown
        //================
        //Usage example:
        //================
        // Data set up
                std::vector<double> result;
                        int ids[]= 1, 2, 3;
                        double weights[] = 12.3, 1.2, 2.1 ;
                        VecCon MyVecCon;
                        std::vector<NeuronSharedPtr> vNeuron;
                        std::vector<double> vWeight;
                        NeuronSharedPtr ptNeuron;
                        for (int i=0; i<=2; i++)
                        ptNeuron.reset(new Neuron(ids[1]));
                        vNeuron.push_back(ptNeuron);
                        vWeight.push_back(0); /
      / weights are set to 0
                        
                        MyVecCon.buildAndAppend(vNeuron, vWeight);
                        MyVecCon.show();
                        for (int i=0; i<=2; i++)
                                vWeight.at(i)=weights[i];
                        
        // Test
                        MyVecCon.setWeight(vWeight); // weight
      s are set to 12.3, 1.2 and 2.1
                        result=MyVecCon.getWeight();
        // Now result is a vector that contains the values 12.3, 1.2 and 2.1 .
See also
getWeight and the unit test files, e.g. runit.Cpp.VecCon.R, for further examples.
Definition at line 235 of file VecCon.cpp.
References Container< Con >::collection.
                                                  
        BEGIN_RCPP
        if (vWeight.empty()) throw std::range_error("[ C++ VecCon::setWeight]:
      Error, vWeight is empty");
        if (vWeight.size() != collection.size()) throw std::range_error("[C++ vecCo
      n::setWeight]: Error, vWeight.size() != collection.size()");
        std::vector<double>::iterator itrWeight = vWeight.begin();
        for(std::vector<ConPtr>::iterator itr = collection.begin(); itr !=
      collection.end(); itr++, itrWeight++)
                (*itr)->setWeight(*itrWeight);
        
        return true;
        END_RCPP
bool VecCon::validate ()
Object validator.
This method checks the object for internal coherence. A try / catch mechanism exits normal execution and returns control to the R terminal in case the contents of the VecCon object are identified as corrupted.
Returns
true in case the checks are Ok.
Exceptions
An std::range error if weight or from are not finite.
See also
The unit test files, e.g., runit.Cpp.VecCon.R, for usage examples.
Reimplemented from Container< Con >.
Definition at line 645 of file VecCon.cpp.
References getId().
                      
        BEGIN_RCPP
        std::vector<int>::iterator itr;
        std::vector<int> vIds = getId();
        sort(vIds.begin(), vIds.end());
        itr=adjacent_find(vIds.begin(), vIds.end());
        if (itr!= vIds.end()) throw std::range_error("[C++ VecCon::validate]:
      Error, duplicated Id.");
        Container<Con>::validate();
        return(true);
        END_RCPP
;
The documentation for this class was generated from the following files:
pkg/AMORE/src/VecCon.h
pkg/AMORE/src/VecCon.cpp