# Unit Tests for the listNeuron class methods
# 
# Author: mcasl
###############################################################################

test.gListNeuron.new.push_back.numberOfNeurons.numOfCons <- function() {
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=11:15)
	nn <- gNeuron$new(id=1, con=lc)
	ln <- gListNeuron$new(nn)
	checkTrue(ln$validate())
	rm(lc, nn, ln)
	
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=11:15)
	nn <- gNeuron$new(id=1, con=lc)
	ln <- gListNeuron$new()
	ln$push_back(nn)
	checkTrue(ln$validate())
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=1:5)
	nn <- gNeuron$new(id=2, con=lc)
	ln$push_back(nn)
	checkTrue(ln$validate())
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=21:25)
	nn <- gNeuron$new(id=3, con=lc)
	ln$push_back(nn)
	checkTrue(ln$validate())
	checkEquals(ln$getId(),1:3)
	checkEquals(ln$numOfNeurons(),3)
	checkEquals(ln$numOfCons(),c(5,5,5))
}


test.gListNeuron.delete <- function() {
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=11:15)
	nn <- gNeuron$new(id=1, con=lc)
	ln <- gListNeuron$new()
	ln$push_back(nn)
	checkTrue(ln$validate())
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=1:5)
	nn <- gNeuron$new(id=2, con=lc)
	ln$push_back(nn)
	checkTrue(ln$validate())
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=21:25)
	nn <- gNeuron$new(id=3, con=lc)
	ln$push_back(nn)
	checkTrue(ln$validate())
	ln$delete(ID=3)
	checkTrue(ln$validate())
	checkEquals(ln$getId(),1:2)	
}


test.gListNeuron.getFrom_fromIsNumeric <- function() {
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=11:15)
	nn <- gNeuron$new(id=1, con=lc)
	ln <- gListNeuron$new()
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=1:5)
	nn <- gNeuron$new(id=2, con=lc)
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=21:25)
	nn <- gNeuron$new(id=3, con=lc)
	ln$push_back(nn)
	checkTrue(ln$validate())
	checkEquals(ln$getFrom(),list(1:5,1:5, 1:5))
}


test.gListNeuron.getFromId_fromIsNumeric <- function() {
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=11:15)
	nn <- gNeuron$new(id=1, con=lc)
	ln <- gListNeuron$new()
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=1:5)
	nn <- gNeuron$new(id=2, con=lc)
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=21:25)
	nn <- gNeuron$new(id=3, con=lc)
	ln$push_back(nn)
	checkTrue(ln$validate())
	checkEquals(ln$getFromId(),list(1:5,1:5, 1:5))
	checkEquals(ln$getFrom(ID=2:3),list(1:5, 1:5))
	checkEquals(ln$getFromId(ID=2:3),list(1:5, 1:5))
}


test.gListNeuron.getFromId_fromIsNeuron <- function() {
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=11:15)
	nn <- gNeuron$new(id=1, con=lc)
	ln <- gListNeuron$new()
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=1:5)
	nn <- gNeuron$new(id=2, con=lc)
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=21:25)
	nn <- gNeuron$new(id=3, con=lc)
	ln$push_back(nn)
	checkTrue(ln$validate())
	ln2 <- gListNeuron$new()
	lc <- gListCon$new()
	lc$populate(FROM=ln$getLdata(), WEIGHT=31:33)
	nn <- gNeuron$new(id=4, con=lc)
	ln2$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=ln$getLdata(), WEIGHT=41:43)
	nn <- gNeuron$new(id=5, con=lc)
	ln2$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=ln$getLdata(), WEIGHT=41:43)
	nn <- gNeuron$new(id=6, con=lc)
	ln2$push_back(nn)
	checkTrue(ln2$validate())
	checkEquals(ln2$getFromId(),list(1:3,1:3, 1:3))
	checkEquals(ln2$getFromId(ID=5:6),list(1:3, 1:3))
}


test.gListNeuron.setWeight.getWeight <- function() {
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=11:15)
	nn <- gNeuron$new(id=1, con=lc)
	ln <- gListNeuron$new()
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=1:5)
	nn <- gNeuron$new(id=2, con=lc)
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=21:25)
	nn <- gNeuron$new(id=3, con=lc)
	ln$push_back(nn)
	checkTrue(ln$validate())
	checkEquals(ln$getWeight(),list(11:15,1:5, 21:25))
	checkEquals(ln$getWeight(ID=1:2),list(11:15,1:5))
	ln$setWeight(list(1:5,5:1,1:5))
	checkEquals(ln$getWeight(),list(1:5,5:1, 1:5))
	checkEquals(ln$getWeight(ID=c(1,3)),list(1:5,1:5))
}


test.gListNeuron.setId.getId <- function() {
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=11:15)
	nn <- gNeuron$new(id=1, con=lc)
	ln <- gListNeuron$new()
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=1:5)
	nn <- gNeuron$new(id=2, con=lc)
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=21:25)
	nn <- gNeuron$new(id=3, con=lc)
	ln$push_back(nn)
	checkTrue(ln$validate())
	ln$setId(11:13)
	checkEquals(ln$getId(),11:13)
	ln$setId(2:3,ID=12:13)
	checkEquals(ln$getId(),c(11,2,3))	
}


test.gListNeuron.is.regular <- function() {
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=11:15)
	nn <- gNeuron$new(id=1, con=lc)
	ln <- gListNeuron$new()
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=1:5)
	nn <- gNeuron$new(id=2, con=lc)
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=21:25)
	nn <- gNeuron$new(id=3, con=lc)
	ln$push_back(nn)
	checkTrue(ln$is.regular())
	lc <- gListCon$new()
	lc$populate(FROM=1:7, WEIGHT=21:27)
	nn <- gNeuron$new(id=4, con=lc)
	ln$push_back(nn)
	checkTrue(!ln$is.regular())
}


test.gListNeuron.select <- function() {
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=11:15)
	nn <- gNeuron$new(id=1, con=lc)
	ln <- gListNeuron$new()
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=1:5)
	nn <- gNeuron$new(id=2, con=lc)
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=21:25)
	nn <- gNeuron$new(id=3, con=lc)
	ln$push_back(nn)
	checkTrue(ln$is.regular())
	lc <- gListCon$new()
	lc$populate(FROM=1:7, WEIGHT=21:27)
	nn <- gNeuron$new(id=4, con=lc)
	ln$push_back(nn)
	checkTrue(ln$select(ID=1:3)$is.regular())
	checkEquals(ln$select(ID=1:3)$getId(),1:3)
}


test.gListNeuron.setFrom.getFrom <- function() {
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=11:15)
	nn <- gNeuron$new(id=1, con=lc)
	ln <- gListNeuron$new()
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=1:5)
	nn <- gNeuron$new(id=2, con=lc)
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=21:25)
	nn <- gNeuron$new(id=3, con=lc)
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:7, WEIGHT=21:27)
	nn <- gNeuron$new(id=4, con=lc)
	ln$push_back(nn)
	ln$setFrom(list(7:1), ID=4)
	checkEquals(ln$getFrom(ID=4), list(7:1))
	ln$setFrom(list(101:105,11:15,5:1,1:7))
	checkEquals(ln$getFrom(ID=4), list(1:7))
	checkEquals(ln$getFrom(), list(101:105,11:15,5:1,1:7))	
}

test.gListNeuron.show <- function() {
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=11:15)
	nn <- gNeuron$new(id=1, con=lc)
	ln <- gListNeuron$new()
	ln$push_back(nn)
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=1:5)
	nn <- gNeuron$new(id=2, con=lc)
	ln$push_back(nn)
	checkTrue(ln$show())	
}


test.gListNeuron.validate <- function() {
	lc <- gListCon$new()
	lc$populate(FROM=1:5, WEIGHT=11:15)
	nn <- gNeuron$new(id=1, con=lc)
	ln <- gListNeuron$new()
	ln$push_back(nn)
	checkTrue(ln$validate())
	ln$push_back("xx")
	checkException(ln$validate(), silent=TRUE)
}